### ISSUE TITLE
Color output broken on Windows cmd/ps with go v1.10.2

### ISSUE THREAD

**Issue by agajdosi** [cucumber/godog#129]
I've just upgraded go from 1.7.6 to 1.10.2 on Windows 7 machine and Godog's color output stopped to work:

```
    Running Integration test in: C:/Users/CDKQE/go/src/github.com/minishift/minishift/out/inte
    gration-test
    Using binary: C:/Users/CDKQE/minishift/minishift.exe
    ←[1;37mFeature: ←[0meap-cd add-on
      Eap-cd add-on imports eap-cd imagestreams and templates, which are then available in Ope
    nShift to the user.
     
    ←[1;37mFeature: ←[0mregistry-route add-on
      registry-route addon exposes the route for the OpenShift integrated registry,
      so that user can able to push their container images directly to registry and deploy it.
     
     
    ←[1;37mFeature: ←[0mxpaas add-on
      Xpaas add-on imports xPaaS templates and imagestreams,
      which are then available in OpenShift to the user.
     
    ←[1;37mFeature: ←[0mBasic
      As a user I can perform basic operations of Minishift and OpenShift
```

With v1.7.6 everything was ok. Only solution now is to disable colors: `--no-color`.

**Comment by l3pp4rd** [comment]
hm, that is an interesting issue, thanks for reporting. will have a look at the colorization libraries to see whether there are any differences

**Comment by l3pp4rd** [comment]
@agajdosi could you try branch https://github.com/DATA-DOG/godog/tree/colors make sure subpackage colors is installed

**Comment by agajdosi** [comment]
@l3pp4rd Tried with branch colors, but it gives an error on Windows:
```
# github.com/DATA-DOG/godog/colors
..\..\DATA-DOG\godog\colors\ansi_windows.go:96:26: cannot convert os.Stdout (type *os.File
) to type syscall.Handle
FAIL    github.com/minishift/minishift/test/integration [build failed]
make: *** [integration] Error 2
```

**Comment by l3pp4rd** [comment]
should be fine now, did not install windows on vm just for these colors

**Comment by agajdosi** [comment]
@l3pp4rd Fully understand. I am happy to help you trying it, will test it tomorrow probably and let you know.

**Comment by agajdosi** [comment]
@l3pp4rd With latest fix of yours I can run the tests, unreadable strings disappeared, however the output is not colored at all in both Command line and PowerShell.

**Comment by l3pp4rd** [comment]
I took `windows 10 enterprise evaluation` virtual box vm and it looks like in command prompt and git for windows bash shell colors are printed fine. I'll leave this for users having this issue to contribute the patch, since cannot replicate it on my own.

**Comment by l3pp4rd** [comment]
Hi @agajdosi are you experiencing this all along?

**Comment by l3pp4rd** [comment]
probably need to enable the flag **ENABLE_VIRTUAL_TERMINAL_PROCESSING** see https://github.com/mattn/go-colorable/issues/18 will check later if that may be done automatically

**Comment by jaysonesmith** [comment]
@agajdosi Are you able to clone [this](https://github.com/jaysonesmith/godog-baseline-example.git) project and try running `go test` please? I'm on a Win7 machine and I'm still able to get colors via both the godog and go test command in a number of different terminal apps.

If you're also able to share an example of your project that demonstrates the issue, I can try running it on my machine to see if it happens.

**Comment by jaysonesmith** [comment]
To add, I'm on go 1.10. I can try a newer version to see if that changes things, too.

**Comment by lonnblad** [comment]
I will close this due to inactivity, please feel free to reopen.
