### ISSUE TITLE
go install not creating binary of GODOG while go get is able to

### ISSUE THREAD

**Issue by iamthadiyan** [cucumber/godog#169]
I am on go version `go1.11.2 linux/amd64`. When the package godog is installed using `go get github.com/DATA-DOG/godog/`, godog executable is created inside `$GOPATH/bin/`. All fine till now.

I am creating an application `myApp `that resides at `$GOPATH/src/` in which under the folder `vendor`, godog package is added. When I try to create a binary out of vendor-ed package, an archive file is created inside `$GOPATH/pkg/linux_amd64/myApp/vendor/github.com/DATA-DOG/` as `godog.a`

How can I create a binary in this scenario? I do not want to do go get again just for the binary.

**Comment by l3pp4rd** [comment]
Hi, binary can built, but you need to go two directories deeper, **cmd/godog** and build the binary

**Comment by l3pp4rd** [comment]
hard to say, maybe it sees that it is a main package and ignores it, I have not used dep. but maybe there is some option to prevent it

Anyway, I suggest to use go modules for next projects

**Comment by lonnblad** [comment]
I will close this due to inactivity, please feel free to reopen.
