### ISSUE TITLE
Pass the feature's name to a step

### ISSUE THREAD

**Issue by festo** [cucumber/godog#175]
Hi @l3pp4rd!

Is there a way to pass the current scenario/feature definition to a step? I would like to log each HTTP requests that we send to our API and I need to attach the current feature name and scenario name. I was thinking to use the hooks somehow but I think if I run the tests parallel that couldn't work.

**Comment by l3pp4rd** [comment]
Hi, yes currently when parallel it will not work, I'm planning to at some point change the gherkin so that each node could have a parent node. that would be a good solution to many cases we have

**Comment by festo** [comment]
Thanks for this quick answer. May I know approximately when do you plan to do it, in weeks or in months or in the far future? :)

**Comment by l3pp4rd** [comment]
I cannot know that, since this project is not related to my daily work. if that is important for you, you can run through the gherkin package and make the change in PR. I think, that can be accepted since that is useful for many parts of code.
