### ISSUE TITLE
Reuse steps across all features without repeating them in every feature directory?

### ISSUE THREAD

**Issue by dipaligulhane** [cucumber/godog#178]
I am working on functional automation using Godog. 
I Want to use common steps definitions directly at the “features” directory. And use these across other features kept in separate directories like “feature1”, “feature2” etc.
For eg. “Login to application” is a common step across all features. So want to define it only once in “login_step_defs_test.go” file. And then reuse the same step across all features without repeating its definition in any other step definition files. Is it possible in Godog?
I have explored “BeforeFeature”, “BeforeScenario” etc options, however, does not suits the problem I am trying to solve. Login is just a simple example I am sharing, I plan to have validation steps which are common across many features to be a part of some step def file and reuse those.
Any way we can achieve it using Godog?
![image](https://user-images.githubusercontent.com/5012177/58823567-a0d37480-8657-11e9-89b6-b68d456d364a.png)

**Comment by l3pp4rd** [comment]
Hi, guess you do not know how go test works, test packages cannot be imported. if you do have common steps (contexts) you should write them not as `_test.go` files, but rather make standard packages. Then you can import it in your root test package and register in the main suite runner context as separate contexts. 

Note, that godog runs tests for a single root package, in most of the cases it is where your main package is. Though, you should not follow java, ruby or php patterns in go, it is a different language and you should understand the practices it advocates
