### ISSUE TITLE
how to run multiple tags with godog?

### ISSUE THREAD

**Issue by eswarisrinivasan** [cucumber/godog#189]
hi, 

Im trying to run multiple scenarios from different feature files. I tried to run them using `godog --tags @login --tags @booking and godog --tags="@login,@booking".` but none of them is working. could you please help?

**Comment by inluxc** [comment]
Just use the same tag in all scenarios that you want to run. 
Scenarios can have multiple tags.
Like: @sanityLoginBooking

But you will a problem with the order of execution.

I normally create a feature for each sequence of execution and yes I repeat scenarios for each execution.

**Comment by MarianMacik** [comment]
Hi guys, I have found by looking at the code and also by running `godog -h` this:

```
-t, --tags=          Filter scenarios by tags. Expression can be:
                           - "@wip": run all scenarios with wip tag
                           - "~@wip": exclude all scenarios with wip tag
                           - "@wip && ~@new": run wip scenarios, but exclude new
                           - "@wip,@undone": run wip or undone scenarios
```

I can create a PR and document it better as this format is different to what Cucumber uses, they use `and`, `not` etc.

**Comment by MarianMacik** [comment]
@lonnblad since there is no information about it in the documentation, can I proceed with a PR to at least mention how multiple tags can be run? Thanks.

**Comment by lonnblad** [comment]
@MarianMacik yes, please do!

if you want to, you could also create a new issue to make it follow Cucumber format

**Comment by lonnblad** [comment]
@MarianMacik Thanks for the contribution!! :)
