### ISSUE TITLE
Feature passes even if I put in wrong data

### ISSUE THREAD

**Issue by mziia** [cucumber/godog#192]
My func:

```
func userEnterLoginAndPassword(log, pas string) error {

	// Page.FindByXPath("//input[@aria-label = 'E-mail']").Fill(log)
	// Page.FindByXPath("//input[@aria-label = 'Пароль']").Fill(pas)

	test := It("should manage user authentication", func() {
		By("Opening page", func() {
			Expect(Page.FindByXPath("//input[@aria-label = 'E-mail']").Fill(log)).To(Succeed())
			Expect(Page.FindByXPath("//input[@aria-label = 'Пароль']").Fill(pas)).To(Succeed())
		})
	})

	if test == false {
		return godog.ErrPending
	}

	return nil
}
```

If I change this

`Expect(Page.FindByXPath("//input[@aria-label = 'E-mail']").Fill(log)).To(Succeed())`

To this

`Expect(Page.FindByXPath("//input[@aria-label = 'blahlalahlalala']").Fill(log)).To(Succeed()) `

I want it to fail, but it pass anyway
What am I doing wrong and how to fix it?

**Comment by l3pp4rd** [comment]
`godog.ErrPending` means the step has no definition and implementation is needed. Use standard generated errors if you want it to fail. `return fmt.Errorf("failed reason")` by the way, just have a look at the godog library tests, if you find it hard to read the examples or documentation.

**Comment by lonnblad** [comment]
I will close this due to inactivity, please feel free to reopen.
