### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by slotaj** [cucumber/godog#195]
Hello, 

I have been trying to google this issue and have seen it happened in the past. I was unable to solve this and thought maybe I could reach out to you guys. When running godog I am getting the failed to compile testmain package: exit status 2 - output: error. I can't find import for vendor/github.com/DATA-DOG/godog but I can visually see it in my vendor folder

Godog version is: v0.7.13
go version go1.13.1 darwin/amd64

Any help would be appreciated, thank you

**Comment by l3pp4rd** [comment]
Hi, maybe temporary you could use module dependency..
Also, can you tell the directory layout for your project, the vendor package works only if it is in GOPATH.
So if you have `$GOPATH/src/myproject/vendor/github.com/DATA-DOG/godog` it should compile fine, if not probably something broke with go 1.3 release built toolchain

**Comment by erikdubbelboer** [comment]
Go 1.13 definitely broke things for godog. Having a `GOPATH` set always causes the ` I can't find import for` error. Running it like `GOPATH= godog` to unset `GOPATH` fixes the issue for now.

**Comment by Mutated1994** [comment]
Hello,

I have been trying to google this issue and have seen it happend in the past. I was unable to solve this and thought maybe I could reach out to you guys. When running godog I am getting the failed to compile testmain package: exit status 2 - output: error. I can't find import for "myproject/vendor/github.com/DATA-DOG/godog" but i can visually see it myproject vendor folder.

Godog version is: v0.7.13
go version go1.12.9 darwin/amd64

And help would be appreciated, thank you!

**Comment by lonnblad** [comment]
I will close this due to inactivity, please feel free to reopen.
