### ISSUE TITLE
Optional parameter when using and not using gherkin.DocString

### ISSUE THREAD

**Issue by mpermperpisang** [cucumber/godog#200]
Hello,

I have 2 scenarios with similar step

**first scenario has this step**
`When client sends a GET request to "ENV:ENDPOINT"`

**second scenario**
```
When client sends a POST request to "ENV:ENDPOINT_4" with body:
    """
    {
      "name": "ENV:NAME",
      "start_time": "ENV:START_TIME",
      "end_time": "ENV:END_TIME",
      "price": ENV:PRICE,
      "email_stakeholders": "ENV:EMAIL_STAKEHOLDERS",
      "event_id": ENV:EVENT_ID
    }
    """
```

**step definition**
`s.Step(`^client sends a ([^\"]*) request to "([^\"]*)"(?: with body:)?$`, apisteps.RequestAPI)`

**function RequestAPI**
```
func RequestAPI(verbose string, request string, body *gherkin.DocString) error {
	fmt.Println("1")

	return nil
}
```

everytime I run the first scenario it always say `Error: func expects 3 arguments, which is more than 2 matched from step`. anyone has experience this? how do you solved it?

thank you

**Comment by l3pp4rd** [comment]
Seems like optional regex blocks are not supported. Maybe godog should check if it is a pointer type missing and pass nil instead (your case the third argument). Will need to check the default cucumber behavior

**Comment by marauderlabs** [comment]
> Will need to check the default cucumber behavior

It does. https://cucumber.io/docs/cucumber/cucumber-expressions/#optional-text

**Comment by mpkorstanje** [comment]
Steps are matched to step definitions by regex/cucumber expression alone. This means that if a step definition includes a docstring or data table, the step should always have a doc string or data table. You can instead create two step definitions and invoke a helper method.

```
^client sends a ([^"]) request to "([^"])"(?: with body:)?$
^client sends a ([^"]) request to "([^"])"$
```

**Comment by lonnblad** [comment]
Based on the answer from mpkorstanje, I will close this issue with wontfix.

BR
Fredrik
