### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by inluxc** [cucumber/godog#203]
The project seems a bit stale, can we create a Discord Server, so we can chat about the project and show our work with it?

At my work we use godog every day, we are implementing in all our projects. they are more than 100 microservices. From API, Frontend and Database tests.

**Comment by inluxc** [comment]
I took the liberty of creating one if anyone would like to join us.
https://discord.gg/zMtWpM

**Comment by l3pp4rd** [comment]
Hi, you can create the group and organize it, I do not have enough time to spare for all this.

**Comment by jaysonesmith** [comment]
Hey @inluxc ! Thanks so much for taking the initiative to set this up! With the inclusion of the project under the wider Cucumber family, I'm actually going to ask that you join us in the Cucumber-BDD slack. :) I've also created a channel there specifically for help with godog. [Join here](https://cucumberbdd-slack-invite.herokuapp.com/)
