### ISSUE TITLE
Set up CircleCI

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/godog#208]
We're moving all repos in this org to CircleCI.

**Comment by jaysonesmith** [comment]
I've got the initial config going but need to get some go declarations and package locations switched over still, before things are passing.

**Comment by lonnblad** [comment]
haven't used circle-ci for a few years, so I don't know what is possible/fairly easy todo these days.

but now we run the tests for go1.10 - go1.12, would be nice to add go1.13 as well

**Comment by jaysonesmith** [comment]
I'm not familiar with Travis' config, so I'll need to look at how it's currently running the tests against older versions of go, good looking out @lonnblad! I've got 1.13 running in Circle now, link to build [here](https://circleci.com/gh/cucumber/godog/11)

I've also released v0.8.0 of godog updating package paths and whatnot away from the DATA-DOG org.

**Comment by jaysonesmith** [comment]
We're now testing 1.13, 1.12, and 1.11 with the more coverage that was being tested in Travis. I added in golint, too.

**Comment by sagikazarmark** [comment]
Maybe a little too late, but how about GitHub Actions? IMHO it's much better than CircleCI.

**Comment by aslakhellesoy** [comment]
What do you find better @sagikazarmark ?

**Comment by sagikazarmark** [comment]
GitHub actions is generally more stable in my opinion, the configuration is much more straightforward and easier to write/read and better integrated into GitHub (obviously) which makes a better overall experience.
