### ISSUE TITLE
readme instructions - should these show cucumber instead of DATA-DOG ?

### ISSUE THREAD

**Issue by martin-flower** [cucumber/godog#211]
the readme says:

`go get github.com/DATA-DOG/godog/cmd/godog`

which leads to :

```
module declares its path as: github.com/cucumber/godog
                but was required as: github.com/DATA-DOG/godog

```

instead should this be:

`go get github.com/cucumber/godog/cmd/godog`

**Comment by lonnblad** [comment]
Thanks for the issue Martin, there is a PR currently being worked on for this:
https://github.com/cucumber/godog/issues/211

**Comment by jaysonesmith** [comment]
@martin-flower All set here. :)
