### ISSUE TITLE
Security error when getting v0.8.0 with go mod

### ISSUE THREAD

**Issue by titouanfreville** [cucumber/godog#212]
Hello, 
I couldn't find the issue in the list so I open a new one. 
When trying to add github.com/cucumer/godog with go mod, it raise a security error regarding the checksum server 

```
go mod tidy             
go: finding github.com/DATA-DOG/godog/gherkin latest
go: downloading github.com/DATA-DOG/godog v0.8.0
go: finding github.com/cucumber/godog/gherkin latest
go: downloading github.com/cucumber/godog v0.8.0
verifying github.com/cucumber/godog@v0.8.0: checksum mismatch
        downloaded: h1:pwbfDlZsYqH55uKW35jLxhBzNYYGncYc9XLnGRfkVtk=
        sum.golang.org: h1:sJ0MaOGfNeJWD+DiBjL4VTwrUJrFdiq5sF5b4wPgS+o=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```
I think you should be alerted on this :) 
Was using github.com/DATA-DOG/godog until now without any issue.

**Comment by titouanfreville** [comment]
When setting no checksum for cucumber/godog: 
verifying github.com/DATA-DOG/godog@v0.8.0: checksum mismatch
        downloaded: h1:tA/nBoOKI7PfHbE9ATVwev8ZbfstOdlNpgDWvoI/u1w=
        sum.golang.org: h1:0Q9dkFbA08jkmv01VihDNo6HLUfvRjvP3eEF8jWA9vg=

SECURITY ERROR

**Comment by jaysonesmith** [comment]
@titouanfreville Thanks for the heads up! It appears it's still trying to grab the data dog version for whatever reason. Hmm. Could you check through your project to see if there's anything that's still trying to pull from the old location that could be messing things up, please?

**Comment by inluxc** [comment]
Clean any trace of the old godog, in GOPATH/src, GOPATH/mod

And get the package again.
`go get github.com/cucumber/godog`

**Comment by titouanfreville** [comment]
Ok. Worked cleanly after cleaning all old references to DATA-DOG path. 
Now have to solve https://github.com/cucumber/godog/issues/213

Thanks :)

**Comment by titouanfreville** [comment]
Seems to also encounter it when downloading without goflags (to install it globally)

```
GOFLAGS="" go get github.com/cucumber/godog
verifying github.com/cucumber/godog@v0.8.0/go.mod: checksum mismatch
        downloaded: h1:FQ2MobPXycdSajAK3inNgLSAKGFmZqbE4S/CExz41Ys=
        sum.golang.org: h1:Cp3tEV1LRAyH/RuCThcxHS/+9ORZ+FMzPva2AZ5Ki+A=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by jaysonesmith** [comment]
Hey @titouanfreville, I'm not familiar with that method, could you point me to where that's suggested? Are you open to trying the current workaround [here?](https://github.com/golang/go/issues/30515#issuecomment-582044819)

**Comment by titouanfreville** [comment]
@jaysonesmith I don't think the issue is related to https://github.com/golang/go/issues/30515#issuecomment-582044819 (though its certainly a nicer way to download dependencies with module and global reach (will try it)). 
I still encounter the security warning when installing from `go mod` when I disable the `GONOSUMDB`.
Did you perhaps change the release code ? (Like published the release once then erase and recreate it ?). Don't think so but it could explain the security error. 

When using no sum db, it installed as expected and work well.

**Comment by jaysonesmith** [comment]
@titouanfreville Hey, good thinking! That might be it. I'll do a patch version and see if that helps.

**Comment by jaysonesmith** [comment]
@titouanfreville I've released v0.8.1, could you give that a shot please and let me know how that goes for you?

**Comment by devholic** [comment]
I had a same issue, but bumping godog version to 0.8.1 fixes this issue 🙂

**Comment by titouanfreville** [comment]
@jaysonesmith Looks good. I could install it on another env without issue and update my working space without the sumdb env. 

Thanks.

**Comment by luqmanshahzad** [comment]
@titouanfreville, I am facing same issue when I use ./network.sh deployCC command while running the test-network. Can you please help me? 
![Screenshot from 2020-09-02 11-12-33](https://user-images.githubusercontent.com/27766292/91938783-0c4e3b00-ed0e-11ea-90f8-b5e10ce6181c.png)

**Comment by titouanfreville** [comment]
You have to change the version if you can. 

The security error is due to a change to the modules after its first upload/download so the version of the commit stored by go is not the same one as the current downlodable one for `0.8.0`.
 You have to go to `0.8.1` if you wish to use this version. 

If you cannot change the version of godog, you can just setup the variable `GONOSUMDB=github.com/cucumber/godog`.

**Comment by Babitabisht** [comment]
@titouanfreville  thanks, this solved the issue

**Comment by lonnblad** [comment]
Thanks @titouanfreville!

**Comment by PureRaidenCloud** [comment]
![image](https://user-images.githubusercontent.com/63286100/113110238-6f1e9b00-9239-11eb-8761-cb8447418e6b.png)
@titouanfreville I've changed the GONOSUMDB=github.com/cucumber/godog, but it changed nothing, can you please help me  figure out this issue ?

**Comment by lonnblad** [comment]
Hi @PureRaidenCloud,
would it be possible to upgrade to `v0.8.1` or the latest `v0.11.0`?

BR
Fredrik

**Comment by titouanfreville** [comment]
Hello @PureRaidenCloud did you solve the issue already ? (sry, was away from godog for some times and did not have time to help). 

The best way to solve is (as indicated by lonnblad), to use v0.8.1 witch is strictly identical to v0.8.0 or later.

Also, this issue should not happen when using go 1.16 as they upgraded the dependencie management system. Now, it allows module version upgrade after release and should not raise error on sumdb anymore (but not sure, need to try for project not created with go 1.16)
