### ISSUE TITLE
Cannot build test suite after migrating to v0.8.0

### ISSUE THREAD

**Issue by titouanfreville** [cucumber/godog#213]
After passing #212 (adding cucmber/godog to the no check DB),
I cannot build my test suite anymore:
```
failed to compile tested package: /Users/titouan/tankyou/gitlab/service/test, reason: exit status 1, output: WORK=/var/folders/9w/mybs723s17q0kdh7l40q_1w00000gn/T/go-build442462247
build github.com/DATA-DOG/godog: cannot load github.com/DATA-DOG/godog: open /Users/titouan/tankyou/gitlab/service/vendor/github.com/DATA-DOG/godog: no such file or directory
```

I made sure to clear all reference to `DATA-DOG/godog` from my code and rebuild modules description and vendor. 

I'll try on a fresh project to check if it only happen when migrating or not.

**Comment by jaysonesmith** [comment]
I'm not certain the cause, but if removing references doesn't do it, could you try running `go clean --modcache` please?

**Comment by titouanfreville** [comment]
Ok. I just forgot the cmd was not installed through the module so it was not updated. Cleaning old CMD for new worked.
Thanks.
