### ISSUE TITLE
Are the Gherkin steps resusable in other feature files? 

### ISSUE THREAD

**Issue by dmholb01** [cucumber/godog#226]
For instance if I have a feature file called login.feature and another feature file called payment.feature, and they need to share similar gherkin steps, (for example: 'Given I login to the application'), would godog allow it? Sorry new to understanding how godog works in comparison to how I've used cucumber in the past.

**Comment by lonnblad** [comment]
Hi @dmholb01 

Yes, you can reuse step definitions between multiple feature files.

**Comment by dmholb01** [comment]
Thanks and what about the step definitions that get generated by godog. If I have step definitions generated in login_test.go, would the steps be considered defined for payment.feature? Or would godog treat them as undefined since the steps are in login_test.go and not in payment_test.go. I don't know maybe I'm overthinking and confusing myself.

**Comment by l3pp4rd** [comment]
No matter what name_test.go files are, within the same go package all steps are shared. 

You can also create separate packages for importing with step definitions for focused logic like web browser page steps (these then can’t be in test files since you will import them in test.go file)

**Comment by lonnblad** [comment]
There is no link between the filenames, so you can define your step definitions in one or multiple go-test files and have one or multiple feature files using them.

As long as the step definitions are registered with the executed test suite, they will be reused across all feature files.

In this example, you would be able to add more feature files that use the same step definitions or split up `godog_test.go` in multiple files.
https://github.com/cucumber/godog/tree/master/_examples/godogs

**Comment by lonnblad** [comment]
I believe the question was answered, so I will close this one. :)
