### ISSUE TITLE
New version broke the build - Getting failed to compile testmain package: exit status 2

### ISSUE THREAD

**Issue by Automationrode** [cucumber/godog#229]
I upgraded godog to 
Godog version is: v0.8.0 using `go get -u github.com/DATA-DOG/godog/cmd/godog`

Now if I try to run godog I am getting failed to compile testmain package: exit status 2

`$ godog
failed to compile testmain package: exit status 2 - output: /var/folders/nd/gr250x_x63ldbgkbqtz3s9xrnnz08m/T/go-build050675974/b001/_testmain.go:17:15: cannot use suite (type *"github.com/cucumber/godog".Suite) as type *"github.com/DATA-DOG/godog".Suite in argument to test.name`

**Comment by lonnblad** [comment]
Hi @Automationrode 

Can you try to update your references from `github.com/DATA-DOG/godog` to `github.com/cucumber/godog` and reinstall godog with `go get -u github.com/cucumber/godog/cmd/godog`.

This has changed because godog has been moved from DATA-DOG to cucumber.

**Comment by Automationrode** [comment]
Thanks for the quick response. 
It works 👍  Great!!
