### ISSUE TITLE
parseImport returns wrong path in Windows

### ISSUE THREAD

**Issue by cananac** [cucumber/godog#233]
https://github.com/cucumber/godog/blob/4267df0fa9e060b4e613f1ca354d4e318259f039/builder_go110.go#L379

Hi,
parseImport function returns:
```
mod.Path + filepath.ToSlash(strings.TrimPrefix(strings.TrimPrefix(rawPath, "_"), mod.Dir))
```
And in Windows, rawPath(```_/C_/Something/x-modules/test```) and mod.Dir(```C:\Something\x-modules```) are populated with different slash formats so mod.Dir cannot be trimmed and I get the error below as an expected result:
```[-o C:\....\go-build148781074\b001\main.a -importcfg C:\....\go-build148781074\b001\importcfg.link -p main -complete -pack C:\....\go-build148781074\b001\_testmain.go]
failed to compile testmain package: exit status 2 - output: C:\....\go-build148781074\b001\_testmain.go:5:2: can't find import: "..../C_/Something/x-modules/test"

**Comment by lonnblad** [comment]
Hi @cananac 

Thanks for reporting the issue!
We will try to take a look at it as soon as possible and if you want to, feel free to submit a PR. :)

// Fredrik
