### ISSUE TITLE
Custom Formatters not compatible with concurrency

### ISSUE THREAD

**Issue by ericmcbride** [cucumber/godog#237]
There was a recent Pr merged before cucumber got a hold of godog that broke the use of using concurrency with custom formatters.

In my opinion, the user who made the custom formatter should be responsible for making it safe to use concurrency, and not the library deciding all users cannot use concurrent custom formatters.  This is the main reason we haven't switched over from DATA-DOG, because concurrency is huge for us, and the ability to use our own custom formatter is huge as well.

Heres the change and id be more then happy to change it back

https://github.com/cucumber/godog/pull/204/files#diff-12f3273da1625fbe0b8ae7f4eefe2c3cR280

**Comment by ericmcbride** [comment]
https://github.com/cucumber/godog/pull/238

**Comment by lonnblad** [comment]
Thanks @ericmcbride for reporting the issue and submitting a PR!

// Fredrik
