### ISSUE TITLE
Can't install godog due to `cannot find package "github.com/cucumber/gherkin-go/v9"`

### ISSUE THREAD

**Issue by dpangier** [cucumber/godog#243]
On installing godog, we get the following error:

```
root@0e9777818284:/go# go get github.com/cucumber/godog/cmd/godog
package github.com/cucumber/gherkin-go/v9: cannot find package "github.com/cucumber/gherkin-go/v9" in any of:
	/usr/local/go/src/github.com/cucumber/gherkin-go/v9 (from $GOROOT)
	/go/src/github.com/cucumber/gherkin-go/v9 (from $GOPATH)
package github.com/cucumber/messages-go/v9: cannot find package "github.com/cucumber/messages-go/v9" in any of:
	/usr/local/go/src/github.com/cucumber/messages-go/v9 (from $GOROOT)
	/go/src/github.com/cucumber/messages-go/v9 (from $GOPATH)
```

**Comment by jaysonesmith** [comment]
Thanks for the heads up! We'll get some info back to you when we can. :)

**Comment by slb5427** [comment]
I am also experiencing this same issue.  We install godog as part of our builds and we weren't running into the issue earlier in the day.  It just started.

**Comment by lonnblad** [comment]
Hi

Could you help me with what version of go you are using, if you are running inside a $GOPATH and also if you are using any dependency management solution.

Thanks!
/ Fredrik

**Comment by lonnblad** [comment]
@dpangier @slb5427 @Automationrode 
We reverted the change, so hopefully it should work again now, sorry for any inconvenience.

**Comment by lonnblad** [comment]
No problem, thanks for reporting!
Now I just have to figure out what the issue was. :)

**Comment by dpangier** [comment]
> Hi
> 
> Could you help me with what version of go you are using, if you are running inside a $GOPATH and also if you are using any dependency management solution.
> 
> Thanks!
> / Fredrik

* go version
go version go1.13.5 linux/amd64
* echo $GOPATH
/go
* pwd
/go
* which go
/usr/local/go/bin/go

No module/dependency management - as per @Automationrode these issues are occurring on a build server that has been working fine up until earlier today. (And now working fine again since the revert)

To duplicate the issue you can run inside a fresh docker container...
```
docker run --rm -i -t golang:1.13
go get github.com/cucumber/godog/cmd/godog
```

**Comment by slb5427** [comment]
Seems to be working for us again thanks.
- go version
1.12.13, and while testing locally seen on 1.12.5

This error was seen while running on a GOPATH.
