### ISSUE TITLE
Fatal Error while injecting value after scenario compilation

### ISSUE THREAD

**Issue by titouanfreville** [cucumber/godog#248]
While implementing an helper library to manage rest api request (cf: https://github.com/ekino/veggies), I made a system witch can pick value and inject them. Doing so, I encounter fatal error when rendering test result with pretty formater.
The line length of the steps I injected the variables in surpassed the longest step without injection so it could not correctly insert the comment. 

I propose a simple fix here: #247

**Comment by lonnblad** [comment]
Thanks @titouanfreville for the contribution!! :)
