### ISSUE TITLE
BeforeScenario using tag

### ISSUE THREAD

**Issue by mpermperpisang** [cucumber/godog#252]
Hello,
if I run scenario using `godog --tags=@web`
can I add `s.BeforeScenario("@web")`?
it will only do something for @web tag. if I run `godog --tags=@mobile`, the BeforeScenario won't do anything

Thanks

**Comment by lonnblad** [comment]
Hi @mpermperpisang, there is no way to that as of now.

What you can do is to get the tags of the scenario sent to the hook, but that would include all tags that are specified for that scenario, not just the once you add as an argument to godog.

BR
Fredrik
