### ISSUE TITLE
Notice - Make sure you install godog with a specified version due to breaking changes on master.

### ISSUE THREAD

**Issue by lonnblad** [cucumber/godog#253]
Hi

**We are doing a change to godog and its dependencies which might break your project.** 
The breaking merge will happen on Monday, March, 23. 

To mitigate the change for you, we suggest that you install and depend on a specific version and not the master branch.

To install a specific version:
```
go get github.com/cucumber/godog/cmd/godog@v0.8.1
```
Adding `@v0.8.1` will install v0.8.1 specifically instead of master.

If you are running within the `$GOPATH`, you would also need to set `GO111MODULE=on`, docker example:
```
GO111MODULE=on go get github.com/cucumber/godog/cmd/godog@v0.8.1
```

**If you want to help verify the release candidate for `v0.9.0`**
Tag `v0.9.0-rc2` can be used to install the coming `v0.9.0` release, the release documentation can be found [here](https://github.com/cucumber/godog/blob/v0.9.0-rc2/release-notes/v0.9.0.md).

BR
the godog team

**Comment by lonnblad** [comment]
@dpangier @slb5427 @Automationrode 
heads up

**Comment by slb5427** [comment]
thank you for the heads up

**Comment by Jonathanbenilan** [comment]
Hello, 
I tried to install version 0.11, and ran into same issue. I solved it by installing version 0.8.
Is it expected to still have the issue with version > 0.9?

**Comment by lonnblad** [comment]
@Jonathanbenilan, could you help me witth some context to your issue?

BR
Fredrik

**Comment by mattwynne** [comment]
Seems to be done now.
