### ISSUE TITLE
Concurrency Support for the Events formatter

### ISSUE THREAD

**Issue by lonnblad** [cucumber/godog#255]
Since we want to have concurrency support to all formatters, we should also add it for the Events formatter.

**Comment by lonnblad** [comment]
work in progress
https://github.com/cucumber/godog/tree/concurrent-events-formatter

**Comment by l3pp4rd** [comment]
Hi @lonnblad I think the events formatter was experimental and is not used. It was made due to the draft for all cucumber implementations, but I do not know the state of it now. Maybe it is replaced by the common protobuf lib and gherkin. @jaysonesmith maybe you know more?

**Comment by jaysonesmith** [comment]
I don’t offhand, but that sounds like it would make sense!

**Comment by lonnblad** [comment]
I guess what would be replaced is the data structure, not really the formatter itself?
