### ISSUE TITLE
godog generated code not handling float and negative values correctly

### ISSUE THREAD

**Issue by dougnukem** [cucumber/godog#257]
This may be a misunderstanding of Cucumber/Gherkin/BDD, I'm trying to follow the Gherkin features defined for The Ray Tracer challenge book: https://pragprog.com/book/jbtracer/the-ray-tracer-challenge

e.g.
```
Feature: Tuples, Vectors, and Points

Scenario: A tuple with w=1.0 is a point
  Given a ← tuple(4.3, -4.2, 3.1, 1.0)
  Then a.x = 4.3
    And a.y = -4.2
    And a.z = 3.1
    And a.w = 1.0
    And a is a point
    And a is not a vector
```
When I run `godog` it produces code that looks to be based on regexp that parses each digit as a \d and also seems to incorrectly capture the negative sign, resulting in weird go code.
```go
func aTuple(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8 int) error {
	return godog.ErrPending
}


func FeatureContext(s *godog.Suite) {
	s.Step(`^a ← tuple\((\d+)\.(\d+), -(\d+)\.(\d+), (\d+)\.(\d+), (\d+)\.(\d+)\)$`, aTuple)
	s.Step(`^a\.x = (\d+)\.(\d+)$`, ax)
	s.Step(`^a\.y = -(\d+)\.(\d+)$`, ay)
...
}
```

Is there a way to structure this or have godog generate code using Cucumber expressions:
https://cucumber.io/docs/cucumber/cucumber-expressions/

I would have expected something like:
```go
func aTuple(arg1, arg2, arg3, arg4 float64) error {
	return godog.ErrPending
}

func FeatureContext(s *godog.Suite) {
	s.Step(`^a ← tuple\({float}, {float}, {float}, {float}\)$`, aTuple)
	s.Step(`^a\.x = {float}$`, ax)
	s.Step(`^a\.y = {float}$`, ay)
...
}
```

**Comment by dougnukem** [comment]
Or is godog just meant to provide guidance on matching feature expressions, it's possible for me to just manually write the FeatureContext and steps myself?

**Comment by lonnblad** [comment]
Hey @dougnukem , yes, you can write your own FeatureContext.

The autocreated code is just to give you a suggestion to get going, but it could probably be better at matching float expressions.

Regarding matching floats, if you take this feature:
```
Feature: godog

    Scenario: fractional godogs
        Given 0.5 godogs
```

You could have a test file like this:
```
package godog_test

import (
	"github.com/cucumber/godog"
)

func godogs(arg1 float64) error {
	return nil
}

func FeatureContext(s *godog.Suite) {
	s.Step(`^(\-*\d+\.\d+) godogs$`, godogs)
}
```

Regarding Cucumber expressions like `{float}`, I believe there is no such support as of now

**Comment by dougnukem** [comment]
@lonnblad Thanks that worked great!

https://github.com/dougnukem/raytracer/blob/371f22fa42e89030a916fc09a548d0f2ab7d5824/tuple_test.go#L82-L97


`go test` results in a github action:
https://github.com/dougnukem/raytracer/runs/502120114#step:4:9
