### ISSUE TITLE
README.md example code have a bug that _examples/godogs/godogs_test.go don't have

### ISSUE THREAD

**Issue by denis-trofimov** [cucumber/godog#261]
Please answer these questions before submitting a bug report.

### What version of godog are you using?
```
> godog -version
Godog version is: v0.8.1
I got it running:
go get -u -f -fix -v -t github.com/cucumber/godog/cmd/godog
```

### What version of Go are you using?
```
> go version
go version go1.11.13 linux/amd64
```

### What did you do?
If possible, provide a recipe for reproducing the error.

I follow the example in README.md
I did steps 1-4 copy-pasting code 

### What did you expect to see?

> Now when you run the godog again, you should see:

$ godog
Feature: eat godogs
  In order to be happy
  As a hungry gopher
  I need to be able to eat godogs

  Scenario: Eat 5 out of 12          # features/godogs.feature:7
    Given there are 12 godogs        # godogs_test.go:10 -> thereAreGodogs
    When I eat 5                     # godogs_test.go:14 -> iEat
    Then there should be 7 remaining # godogs_test.go:22 -> thereShouldBeRemaining

1 scenarios (1 passed)
3 steps (3 passed)

### What did you see instead?

1. I have discovered that `cannot find package "github.com/cucumber/messages-go/v9"`
and used `github.com/cucumber/messages-go` to get the code to build.
1.  $ godog
    failed to compile tested package: /src/godogs, reason: exit status 2, output: WORK=/tmp/go-build686601227
    # godogs [godogs.test]
    ./godogs_test.go:35:19: cannot use func literal (type func(*messages.Pickle)) as type func(interface {}) in argument to s.BeforeScenario

### Additional context

Changes to fix are minimal. I can come up with a PR later.
In my working dir I solved it 

```go
func FeatureContext(s *godog.Suite) {
	s.Step(`^there are (\d+) godogs$`, thereAreGodogs)
	s.Step(`^I eat (\d+)$`, iEat)
	s.Step(`^there should be (\d+) remaining$`, thereShouldBeRemaining)

	s.BeforeScenario(func(interface{}) {
		Godogs = 0 // clean the state before every scenario
	})
}
```

**Comment by lonnblad** [comment]
Hi @denis-trofimov 

Thanks for the issue, I believe the README.md was updated separately from a PR we merged, so when we reverted that PR, we missed to revert the README.md.

The example that the README.md is based on can be found [here](https://github.com/cucumber/godog/blob/master/_examples/godogs) as well.

**Comment by lonnblad** [comment]
Updated the README.md, thanks again!

**Comment by denis-trofimov** [comment]
My thanks to you, Fredrick, for maintaining this useable software!16:04, 15 марта 2020 г., "Fredrik Lönnblad" <notifications@github.com>:
Updated the README.md, thanks again!

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты
