### ISSUE TITLE
[Question] custom snippets template

### ISSUE THREAD

**Issue by aledbf** [cucumber/godog#277]
Hi, is it possible to use a custom template and create a file instead of stdout?

**Comment by lonnblad** [comment]
Hi @aledbf, thanks for the question!

We don't support writing to a file as of now, we are planning to add that.
Here is the discussion: #205 

Could you explain a bit more what you were thinking regarding custom templates?

BR
Fredrik

**Comment by aledbf** [comment]
> Here is the discussion: #205

:+1: 

> Could you explain a bit more what you were thinking regarding custom templates?

Sure, add boilerplate we need in order to reduce the required changes to the output
(like BeforeScenario inside FeatureContext)

**Comment by aledbf** [comment]
@lonnblad related to #205, it could be possible to not run the tests but only check if the feature is in "sync"? Like just output the missing code without running the tests

**Comment by jaysonesmith** [comment]
@aledbf Do you mean something like a dry run behavior?

**Comment by jaysonesmith** [comment]
> > Here is the discussion: #205
> 
> 👍
> 
> > Could you explain a bit more what you were thinking regarding custom templates?
> 
> Sure, add boilerplate we need in order to reduce the required changes to the output
> (like BeforeScenario inside FeatureContext)

I'm not sure I follow what you're specifically asking about here, would you be able to give me an example, please?

**Comment by aledbf** [comment]
> Do you mean something like a dry run behavior?

Yes.

**Comment by aledbf** [comment]
Closing. I solved this not using godog binary but with a custom one. Thanks
