### ISSUE TITLE
Binary file can be download from the GitHub release

### ISSUE THREAD

**Issue by LinuxSuRen** [cucumber/godog#280]
**Is your feature request related to a problem? Please describe.**
In my use case, I use godog as a command line. I always compile the source code into a binary file in my pipeline. It might bring some unknown problems.

**Describe the solution you'd like**
I was wondering if you can provide a binary file to let people download them directly.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by jaysonesmith** [comment]
Heya @LinuxSuRen, I'm not entirely sure about whether this is currently possible, but thanks for putting it on our radar!

**Comment by lonnblad** [comment]
Hi @LinuxSuRen 

Which operating system and platform are you interested in and how would you want to access the binary?
Would uploading the binary to the github release be sufficient?

**Comment by LinuxSuRen** [comment]
@lonnblad Yes, it'll be perfect which I can download it from GitHub release page.

**Comment by lonnblad** [comment]
@LinuxSuRen
Great, what Operating System and Platform would you want?
Linux and amd64? or something else?

**Comment by LinuxSuRen** [comment]
We can use [goreleaser](https://github.com/jenkins-zh/jenkins-cli/blob/master/.goreleaser.yml) to achieve it.

**Comment by lonnblad** [comment]
I just made a simple manual solution for now, but feel free to create a PR that would automate it using Circle-CI or improve the manual solution.

**Comment by LinuxSuRen** [comment]
It's pretty easy. See also https://github.com/jenkins-zh/jenkins-cli/blob/master/.github/workflows/release.yaml

**Comment by lonnblad** [comment]
If we want to use [goreleaser](https://goreleaser.com/) and automate the process, I think these links are good to look at:
- [quick-start](https://goreleaser.com/quick-start/)
- [circle-ci](https://goreleaser.com/ci/circle/)
- [homebrew](https://goreleaser.com/customization/homebrew/)

**Comment by lonnblad** [comment]
Uploaded darwin (amd64) and linux (amd64) for v0.10.0 and will start to upload darwin (amd64) and linux (amd64, arm64) for subsequent releases. I have also created another issue to automate the process #334.
