### ISSUE TITLE
can't find import: error on v0.9.0

### ISSUE THREAD

**Issue by sithembiso** [cucumber/godog#281]
### What version of godog are you using?
```
Godog version is: v0.9.0
```

### What version of Go are you using?
```
go version go1.14 darwin/amd64
```

### What did you do?
I tried to install Godog using the instructions on the README. I ran the two commands:
```
go get github.com/cucumber/godog/cmd/godog@v0.9.0
```
Inside my project (go module)

And then outside them project `$GOPATH` I ran the following command:
```
GO111MODULE=on go get github.com/cucumber/godog/cmd/godog@v0.9.0
```

### What did you expect to see?
I expected Godog to run without errors as it did before I moved from the `DATA-DOG` version.

### What did you see instead?
I keep running into this error:
```
failed to compile testmain package: exit status 2 - output: /var/folders/gs/3x_71ksj0pj4c3zmltrzvb500000gn/T/go-build235022053/b001/_testmain.go:4:2: can't find import: "<my-package>/vendor/github.com/cucumber/godog"
```

### Additional context
I migrated my repository from `dep` to `go mod` and that's when Godog started breaking.

**Comment by titouanfreville** [comment]
@sithembiso (Just to be sure), did you check it was well installed with `modules` ? Does it appear in your go.mod and did you run `go mod vendor` ?
If so, how did you import it into your project ?

**Comment by sithembiso** [comment]
Thank you for the reply @titouanfreville. Everything looks fine as far as I can see.
`go.mod`:
```
...
github.com/cucumber/gherkin-go v5.1.0+incompatible
github.com/cucumber/godog v0.9.0
github.com/cucumber/messages-go/v10 v10.0.3
...
```
And yes I did run `go mod vendor` (see attached)
![Screenshot 2020-04-14 at 12 54 50](https://user-images.githubusercontent.com/6559905/79217435-26ff4080-7e4f-11ea-90bc-6802e94f2d0d.png)

I have a package with tests, and the imports look like this:
```
...
"github.com/cucumber/godog"
"github.com/cucumber/gherkin-go"
messages "github.com/cucumber/messages-go/v10"
...
```

**Comment by sithembiso** [comment]
Interesting thing @titouanfreville, I moved my whole repository out of the $GOPATH to my Desktop and ran `godog` from there and it worked. Any idea what could be the cause?

**Comment by titouanfreville** [comment]
It could be an issue on golang side. It looks like the import from modules vendor conflicts with the natural import from the GOPATH. https://github.com/golang/go/wiki/Modules#how-to-define-a-module

**Comment by sithembiso** [comment]
Thank you for the resource, I think I missed a step. Following that guide has solved my issue. Closing...
