### ISSUE TITLE
Can't find godog unix executable in bin folder.

### ISSUE THREAD

**Issue by shubhamVishal4495** [cucumber/godog#283]
I tried installing godog v 0.8.1 but after installing no godog executable is found in $GOPATH/bin.
Please have a look into this. What could have been wrong?

What version of godog are you using?
godog@v0.8.1
What version of Go are you using?
go1.13.10 darwin/amd64

What did you do?
go get github.com/cucumber/godog/cmd/godog@v0.8.1 it did not work so ran this 
GO111MODULE=on go get github.com/cucumber/godog/cmd/godog@v0.8.1 

What did you expect to see?
godog unix executable in $GOPATH/bin folder

 What did you see instead?
Missing executable file

**Comment by jaysonesmith** [comment]
Hi @shubhamVishal4495,

* Are you trying to install godog from **on** or **off** your GOPATH?
* Do you get any output when you try installing the package?
* Are you able to install 0.9.0?

I just tried to reinstall 0.8.1 and was able to do it successfully:

```
╭─00:02 jaysonsmith@MAC ~/dev/code/foo/fci ‹master›
╰─> ls $GOPATH/bin | grep godog
╭─00:02 jaysonsmith@MAC ~/dev/code/foo/fci ‹master›
╰─> GO111MODULE=on go get github.com/cucumber/godog/cmd/godog@v0.8.1                                                                                                 
go: found github.com/cucumber/godog/cmd/godog in github.com/cucumber/godog v0.8.1
╭─00:02 jaysonsmith@MAC ~/dev/code/foo/fci ‹master›
╰─> ls $GOPATH/bin | grep godog
godog
```

**Comment by lonnblad** [comment]
I will close this due to inactivity, please feel free to reopen.
