### ISSUE TITLE
boolean parameter

### ISSUE THREAD

**Issue by martin-flower** [cucumber/godog#284]
As I understand it, it is possible to have numeric and string parameters in statements, such as:
`Then there should be 7 remaining`
Is it possible to have a boolean parameter, such as
`Then the response should be "true"`

**Comment by jaysonesmith** [comment]
Heya @martin-flower! 

There isn't a built-in way to do that, but the following should let you use a string to accomplish the same thing:

```go
func thingsMustBe(status string) error {
	statusBool, err := strconv.ParseBool(status)
	if err != nil {
		return err
	}

	if !statusBool {
		return fmt.Errorf("false")
	}

	return nil
}
``` 

Let me know if that helps!

**Comment by martin-flower** [comment]
Thanks Jaysone! Yes, this is what I've done, but wanted to check if there was a better way.

**Comment by jaysonesmith** [comment]
Not currently! Perhaps something could be added with Cucumber Expressions at some point, but ultimately I think everything comes down to regex. :)
