### ISSUE TITLE
ConcurrentFormatter issue for custom formatters when combining builtin formatters

### ISSUE THREAD

**Issue by ericmcbride** [cucumber/godog#285]
We had a custom formatter that would run in the background, while progress formatter would be what was outputted to stdout. The code we used was based off what was found in this issue:
https://github.com/cucumber/godog/issues/130

We upgraded to the newer version of Cucumber's godog from the old godog (we are on 0.9.0) and now with the introduction of the ConcurrentFormatter interface, the Copy method breaks everything, since we dont have a handle to the Progress Formatter.  So neither formatter will work if ran together.  There is nothing to copy persay, but the results dont appear we just end up with the following:

![Screen Shot 2020-04-17 at 3 35 20 PM](https://user-images.githubusercontent.com/9321550/79611854-1ce47880-80c1-11ea-836f-bdfdb65227ca.png)

The rest of the output is fine, but since we arent implementing anything in Copy (we cant, theres no handle to progress or basefmt) We end up with this, which isn't any good. Does anyone have any suggestions?  I'd hate to not use the newer version, because the Proto / AST with actual node ids, is much nicer then the old implementation with the busted parent pointers.

**Comment by jaysonesmith** [comment]
Hey @ericmcbride! Thanks for bringing this up! I'm not particularly familiar with that section of things, but I've sent a link to this issue to someone who may be able to answer. He hasn't been able to work on the project as of late, but may be able to share something.

**Comment by ericmcbride** [comment]
Any update?

**Comment by lonnblad** [comment]
hey @ericmcbride, sorry for not answering before, would you be able to share the code of your custom formatter?

**Comment by inluxc** [comment]
Is there anyone working in this issue?

**Comment by ericmcbride** [comment]
Sorry ive gotten busy with work!  Its literally the code from that issue + the new sync stuff thats required.  The formatter is still busted, we have been running it without concurrency but it sucks.

**Comment by lonnblad** [comment]
@ericmcbride are you running the progress + cucumber formatters like in #130 ?

It might be that this is actually solved on master (no official release yet), when using the new TestSuiteContext and ScenarioContext.

The key differences in v0.10.0 to v0.9.0 will be concurrency support in all formatters, concurrency will be for scenarios instead of features and the feature hooks are gone.

```// godog v0.10.0 (coming release)
func InitializeTestSuite(ctx *godog.TestSuiteContext) {
	ctx.BeforeSuite(func() { Godogs = 0 })
}

func InitializeScenario(ctx *godog.ScenarioContext) {
	ctx.BeforeScenario(func(*godog.Scenario) {
		Godogs = 0 // clean the state before every scenario
	})

	ctx.Step(`^there are (\d+) godogs$`, thereAreGodogs)
	ctx.Step(`^I eat (\d+)$`, iEat)
	ctx.Step(`^there should be (\d+) remaining$`, thereShouldBeRemaining)
}```

**Comment by lonnblad** [comment]
Also, I would really like if we could have a test suite for custom formatters, so that we don't break things for them.

**Comment by lonnblad** [comment]
I will be out tomorrow, but other than that, if they need, have them give me a call or message me on slack and I can help them as well!

**Comment by lonnblad** [comment]
Combined formatters have also been discussed here #205

**Comment by lonnblad** [comment]
Hi, I will close this issue due to inactivity.

Feel free to reopen!
BR
Fredrik
