### ISSUE TITLE
Issue on  "go get   github.com/cucumber/godog/cmd/godog"

### ISSUE THREAD

**Issue by preetesh-sharma** [cucumber/godog#287]
Please answer these questions before submitting a bug report.

### What version of godog are you using?
```
> godog -version
```v0.9.0

### What version of Go are you using?
```
> go version
```1.13.1

### What did you do?
If possible, provide a recipe for reproducing the error.
following is the docker file contents
FROM golang:1.13.1
RUN mkdir -p $GOPATH/src/godogs
COPY godogs/ $GOPATH/src/godogs/
WORKDIR $GOPATH/src/godogs
RUN go get -d -v ./...
RUN go get   github.com/cucumber/godog/cmd/godog
CMD ["godog","features/Upgrade_regression.feature"]

### What did you expect to see?
go get   github.com/cucumber/godog/cmd/godog
ran successfully 
### What did you see instead?
ackage github.com/cucumber/gherkin-go/v11: cannot find package "github.com/cucumber/gherkin-go/v11" in any of:
	/usr/local/go/src/github.com/cucumber/gherkin-go/v11 (from $GOROOT)
	/go/src/github.com/cucumber/gherkin-go/v11 (from $GOPATH)
package github.com/cucumber/messages-go/v10: cannot find package "github.com/cucumber/messages-go/v10" in any of:
	/usr/local/go/src/github.com/cucumber/messages-go/v10 (from $GOROOT)
	/go/src/github.com/cucumber/messages-go/v10 (from $GOPATH)

### Additional context
Add any other context about the problem here.

**Comment by jaysonesmith** [comment]
Hi @preetesh-sharma! Please take a look at this [pinned issue](https://github.com/cucumber/godog/issues/253) about installing a specific version as it should help you out based on your docker steps. Thanks

**Comment by jaysonesmith** [comment]
If you're still experiencing issues installing afterward, please reopen this issue.

**Comment by preetesh-sharma** [comment]
This doesnt fix the issue, I am doing loops here, I am trying to run godog in docker, I have an entire project built on godog,  I have been using it since Jan 2020, locally everything is working fine, but with the DockerFile content given above, this never works, even with a specific version, Can this be documented properly in readme.

**Comment by jaysonesmith** [comment]
Hi @preetesh-sharma, I'm sorry you're frustrated about what's going on, I totally get it. :( Can you tell me if you're using go modules or some other dependency manager? Additionally, it looks like you've set up the project in your container to be **on** your gopath, I'd like to confirm that's how you intend it? Is this how you have things locally, as well?

I've spent a little time working on this, but I'll need to look at it later. Thanks for providing the info above to help me understand your environment further. :)

**Comment by preetesh-sharma** [comment]
Yes, I have the project set up in the go path locally and I am not using any dependency manager as of now.

**Comment by jaysonesmith** [comment]
Hey, sorry I haven't gotten to this yet @preetesh-sharma !

**Comment by lonnblad** [comment]
Hi @preetesh-sharma,

what happens if you change `RUN go get   github.com/cucumber/godog/cmd/godog` to `RUN GO111MODULE=on go get github.com/cucumber/godog/cmd/godog@v0.9.0`?

**Comment by gradureaufcms** [comment]
I had the same problem but I was just getting started with godog.
I found out that the documentation provides examples relying on cucumber/gherkin-go (DataTable etc...) however godog generated code relying on google grpc (pickle table etc...).
I suspect that the current code base does not provide cucumber/gherkin-go anymore :]
Is this a breaking change ?

**Comment by lonnblad** [comment]
> I had the same problem but I was just getting started with godog.
> I found out that the documentation provides examples relying on cucumber/gherkin-go (DataTable etc...) however godog generated code relying on google grpc (pickle table etc...).
> I suspect that the current code base does not provide cucumber/gherkin-go anymore :]
> Is this a breaking change ?

godog needs both `cucumber/gherkin-go` and `cucumber/messages-go`, where gherkin-go is the gherkin parser and messages-go are the cucumber messages.

The generated code only depends on `messages-go`, since it doesn't need the gherkin-parser.

**Comment by HabibMAALEM** [comment]
Hi,

Same issue here

**Comment by lonnblad** [comment]
Hi @HabibMAALEM, do you have the same problem with docker or in general?

What happens if you do as the suggestion from Jayson and me? Using this:
`GO111MODULE=on go get github.com/cucumber/godog/cmd/godog@v0.9.0`

**Comment by caquillo07** [comment]
Hello! Im having the same issue with gherkin, and using the flag doesnt seem to do the trick

```
➜  GO111MODULE=on go get github.com/cucumber/godog/gherkin@v0.9.0  
go get github.com/cucumber/godog/gherkin@v0.9.0: module github.com/cucumber/godog@v0.9.0 found, but does not contain package github.com/cucumber/godog/gherkin

```

**Comment by lonnblad** [comment]
Hi @caquillo07, you are trying to install a pkg **gherkin**, which doesn't exist.

If you want to install godog as a binary, try using this instead:
`GO111MODULE=on go get github.com/cucumber/godog/cmd/godog@v0.9.0`

**Comment by lonnblad** [comment]
I will close this due to inactivity, please feel free to reopen.
