### ISSUE TITLE
Move the formatters to an internal package.

### ISSUE THREAD

**Issue by lonnblad** [cucumber/godog#319]
To create a bit more structure and to decouple the code base in the root directory of the repository, I would like to move the formatters to its own internal package.

**Comment by aslakhellesoy** [comment]
We've started to do this over in the monorepo:

* https://github.com/cucumber/cucumber/tree/master/html-formatter
* https://github.com/cucumber/cucumber/tree/master/demo-formatter

The idea is to publish formatters as libraries. Their public API is a function that accepts a stream of cucumber messages. The formatter libraries can be used inside Cucumber implementations, but they can also be published as command line tools.

By keeping them in the monorepo we can more easily ensure that various implementations behave the same. For the more complex ones we can do this using a shared set of test data (and expected output) like we're doing for gherkin.

What are the formatters you want to move out? Would you consider moving them to the monorepo? It's always interesting to add another one - any slight inconcistency is an opportunity for improvement!

**Comment by lonnblad** [comment]
I believe that we should work towards moving the formatters to the monorepo as a long term goal, but my aim with this improvement is to continue the work to decouple different parts of godog, so it will be easier to work with whole project.

There are still issues with how godog does some things that need to be solved before we can use more of the cucumber messages, an example is that the timestamps in the protobuf messages are not compatible with how godog handle timestamps during testing.
