### ISSUE TITLE
Request: option to provide features not from filesystem

### ISSUE THREAD

**Issue by zhammer** [cucumber/godog#328]
Hi, I'm curious if y'all would be up allowing a way to provide feature files to `godog.TestSuite` that is not just passing file paths. Our use case is that we'd like to package a test tool as a binary using godog and ship features as static files in the binary using https://github.com/markbates/pkger. Here we'd have he feature file bodies and names; however, the TestSuite wouldn't be able to parse them from a list of filesystem Paths.

Happy to discuss different ways this could work!

https://github.com/cucumber/godog/blob/28ad994ad150cf84838309251c8f23a46fee7b35/options.go#L54-L55

**Comment by lonnblad** [comment]
Sounds interesting, maybe when building the godog testrunner we could have an include functionality that would embed the feature files you pass.

Something like: `> godog build -i -o godog.test features` would build a test runner binary which embeds the features dir.

**Comment by zhammer** [comment]
Yep that’d be nice. We have our own golang cli that uses the godog package directly so wouldn’t immediately need the cli option, but I do like the idea of including packaged feature files in the godog cli tool itself

**Comment by lonnblad** [comment]
Were you thinking something like:
```
type GherkinFile struct {
  Name    string
  Content []byte
}

type Options struct {
  ...
  Files []GherkinFile
}
```

and let your code read the content from pkger?

**Comment by lcarrazana** [comment]
Looking for the exact same functionality.
I'm using pkger for embedding all static files, and would like to also do it for godog feature files.

**Comment by lonnblad** [comment]
@lcarrazana would you want to use it in a similar way as zhammer, or would you use the godog CLI directly?

**Comment by vearutop** [comment]
Done with https://github.com/cucumber/godog/pull/476.
