### ISSUE TITLE
How can I run a specific scenario in a feature file?

### ISSUE THREAD

**Issue by Bradbev** [cucumber/godog#337]
Hi team,
I currently have an existing Gherkin based test system that allows scenarios to be run by name.  I'm trying to get the same sort of workflow from Godog and I'm struggling to see how to best implement it.  The basic workflow is that a file will contain more than one scenario, but I only wish to run one.  I intend to write a VSCode plugin that allows users to click on a scenario to run it.

Thanks!
Brad

**Comment by lonnblad** [comment]
Hey @Bradbev 

I believe you can achieve what you want already today, godog has support for running scenario by line number.
`godog features/godogs.feature:7`

BR Fredrik

**Comment by lonnblad** [comment]
Also, I would personally love to have this plugin! 😄

**Comment by Bradbev** [comment]
@lonnblad  - Thanks!!  I'll keep the group informed if I manage to make my plugin :)

**Comment by Bradbev** [comment]
Seems I was too excited.  I don't use the godog binary to launch my tests - instead I fold them into my own code and launch using godog.RunWithOptions.  (I'm on godog 0.9.0).  I can't obviously see how to specify the line.  I'll go digging through the godog code, but was wondering if you knew off hand how that worked.

**Comment by lonnblad** [comment]
Sure, if you look in the `Options` struct, you will see a property: `Paths []string`, set it to `[]string{"<file_name>:<line_number>"}` for the file and line you want to run

**Comment by Bradbev** [comment]
Ah, I got it working!  Entirely my fault - I was expecting something more explicit in the Options struct.  I also do some feature pre-processing, which was messing up on the line number.  And finally, I was trying to run an Example by line number, not a Scenario.  
Thanks very much!

**Comment by lonnblad** [comment]
Technically, the godog backend would have support for just running one specific example, but I don't believe that is supported by the API nor the CLI as of now.

Maybe a future improvement to godog and the plugin...
