### ISSUE TITLE
godog --format=cucumber not including examples in output

### ISSUE THREAD

**Issue by PeterJFerrarotto** [cucumber/godog#338]
Please answer these questions before submitting a bug report.

### What version of godog are you using?
`v0.10.0`

### What version of Go are you using?
`go1.13.10`

### What did you do?
I have a `Scenario Outline` with an `Examples` section, and I run `godog --format=cucumber (feature directory)/(file name):(test line)` (replacing stuff in parentheses with appropriate values). I've also tried just doing `godog --format=cucumber (feature directory/file name)`.

### What did you expect to see?

I expect to see `type: "scenario outline"` with an `examples` json value.

### What did you see instead?

I see `type:"scenario"` with no `examples` json value.

### Additional context

I also have a `Background` section, if that matters at all

**Comment by lonnblad** [comment]
Hey @PeterJFerrarotto, thanks for reporting the issue!

Would you be able to create a gist with code that reproduces the issue?

BR Fredrik

**Comment by lonnblad** [comment]
Hi, I will close this issue due to inactivity.

Feel free to reopen.
BR
Fredrik
