### ISSUE TITLE
godog installation error(Windows and Mac)

### ISSUE THREAD

**Issue by josephribeirosantos** [cucumber/godog#342]
Please answer these questions before submitting a bug report.

### What version of godog are you using?
```
> godog -version
I couldn't install godog on the machine

### What version of Go are you using?
```
> go version
go version go1.15.1 windows/amd64

### What did you do?
If possible, provide a recipe for reproducing the error.
insert the command in the terminal: go get github.com/DATA-DOG/godog/cmd/godog 

### What did you expect to see?
godog installed

### What did you see instead?
the command go get github.com/DATA-DOG/godog/cmd/godog command is not working

Return:
cannot find package "github.com/cucumber/messages-go/v10" in any of:
        C:\Go\src\github.com\cucumber\messages-go\v10 (from $GOROOT)
        C:\Users\Joseph Santos\go\src\github.com\cucumber\messages-go\v10 (from $GOPATH)
cannot find package "github.com/cucumber/gherkin-go/v11" in any of:
        C:\Go\src\github.com\cucumber\gherkin-go\v11 (from $GOROOT)
        C:\Users\Joseph Santos\go\src\github.com\cucumber\gherkin-go\v11 (from $GOPATH)

### Additional context

When trying to carry out the command go get github.c
![godog-error1](https://user-images.githubusercontent.com/50014912/92312371-e3e96980-efb7-11ea-8baa-012854b99b6f.jpg)
![godog-error2](https://user-images.githubusercontent.com/50014912/92312372-e4820000-efb7-11ea-90fa-8c977dc009bc.jpg)
![godog-error3](https://user-images.githubusercontent.com/50014912/92312373-e4820000-efb7-11ea-9607-f43415a9a3d9.jpg)
![godog-error4](https://user-images.githubusercontent.com/50014912/92312374-e51a9680-efb7-11ea-8a42-5455a19716f5.jpg)
![godog-error5](https://user-images.githubusercontent.com/50014912/92312375-e51a9680-efb7-11ea-96a1-c891943f0535.jpg)
![godog-error6](https://user-images.githubusercontent.com/50014912/92312376-e5b32d00-efb7-11ea-9fa9-2cd66c0050dc.jpg)
![godog-error7](https://user-images.githubusercontent.com/50014912/92312377-e5b32d00-efb7-11ea-83b8-1f3240f0bcb9.jpg)
![godog-error8](https://user-images.githubusercontent.com/50014912/92312378-e5b32d00-efb7-11ea-8b92-4e28c643519a.jpg)

om/DATA-DOG/godog/cmd/godog on Windows 10 by Git Bash or CMD prompt command. (Bearing in mind that the environment variables are configured, and the Go language is installed on the computer).

A criticism is returned, mentioned above, and the godog is not installed.

**Comment by lonnblad** [comment]
Hey @josephribeirosantos, thanks for reporting the issue!

Can you try running `go get ...` with `GO111MODULE=off`.

BR Fredrik

**Comment by lonnblad** [comment]
Hi, I will close this issue due to inactivity.

Feel free to reopen.
BR
Fredrik

**Comment by ourdennis** [comment]
maybe wrong setting for GOOS e.g. GOOS=linux? I made same mistake. T.T
