### ISSUE TITLE
List all existing tags

### ISSUE THREAD

**Issue by mdelapenya** [cucumber/godog#343]
Hi! I'd like to know iff it's possible to list all existing tags, the same way it's possible to list all the step definitions.

**Comment by aslakhellesoy** [comment]
No, you'd have to write your own tool to do that.

Please use the [support](https://cucumber.io/tools/cucumber-open/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.

**Comment by mdelapenya** [comment]
Ah sorry, I did not know about those forums, I'll take a look there first. Thanks!
