### ISSUE TITLE
Trouble with github.com/cucumber/gherkin-go/v11

### ISSUE THREAD

**Issue by josefinkarlssonn** [cucumber/godog#345]
Please answer these questions before submitting a bug report.

### What version of godog are you using?
```
> godog -version
Godog version is: v0.8.0
```

### What version of Go are you using?
```
> go version
```

### What did you do?
If possible, provide a recipe for reproducing the error.

Im trying to use command godog and feature written out

### What did you expect to see?
I expected to see some kind of result writing out the feature

### What did you see instead?
../../../go/src/github.com/cucumber/godog/internal/parser/parser.go:14:2: cannot find package "github.com/cucumber/gherkin-go/v11" in any of:
        /usr/local/Cellar/go/1.15.2/libexec/src/github.com/cucumber/gherkin-go/v11 (from $GOROOT)
        /Users/Josefin/go/src/github.com/cucumber/gherkin-go/v11 (from $GOPATH)

**Comment by lonnblad** [comment]
Hey @josefinkarlssonn 

It looks like there is a strange conflict between the installed godog binary and godog in src.
godog v0.8.* doesn't have a dependency to gherkin-go

If you need to stay on version `0.8`, could you try and upgrade to `v0.8.1`
`go get -u github.com/cucumber/godog/cmd/godog@v0.8.1`

BR Fredrik

**Comment by josefinkarlssonn** [comment]
Thank you for answering.
I have now tried that command but still get the same error.. Can I somehow delete the old version and reinstall v.0.8.1?

The error is happening in file /go/src/github.com/cucumber/godog/internal/parser/parser.go:13:2, and the import statement contain v11..

**Comment by lonnblad** [comment]
if you try and remove `../go/src/github.com/cucumber/godog` and then run `go get github.com/cucumber/godog/come/godog@v0.8.1` again?

**Comment by lonnblad** [comment]
you can also remove `../go/bin/godog` before reinstall

**Comment by lonnblad** [comment]
if it doesn't work, can you run `go env` as well and paste the result

**Comment by josefinkarlssonn** [comment]
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/josefin/Library/Caches/go-build"
GOENV="/Users/josefin/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/josefin/go/pkg/mod"
GONOPROXY="github.com/X"
GONOSUMDB="github.com/X"
GOOS="darwin"
GOPATH="/Users/josefin/go"
GOPRIVATE="github.com/X"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/josefin/MyGherkinTest/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/05/pnx37v1s3tj07yjw6dcm8k2h0000gn/T/go-build876099378=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by lonnblad** [comment]
did it work to remove the godog folder and binary and then reinstall godog?

**Comment by josefinkarlssonn** [comment]
Now the error is gone, it says no scenarios and no steps when i run godog but that is another problem to dive into :) 

Thank you very much for all the help, have a beautiful day!

**Comment by lonnblad** [comment]
sweet, happy to help!

have a nice day!
