### ISSUE TITLE
What is the use of calling testing.M.Run() in TestMain?

### ISSUE THREAD

**Issue by hansbogert** [cucumber/godog#351]
in the [faq](https://github.com/cucumber/godog#user-content-running-godog-with-go-test) there is an example of TestMain

However it calls `testing.M.Run()`, I'm not sure this adds anything useful, in our case it's even detrimental as it does not handle the situation well  when running with Go's `-race` option in combination with the env variable `GORACE=exitcode=0`. 
Also it always seems to cause warning of : 

    ...
    testing: warning: no tests to run
    ...

For now I've removed it in our case, is there any side-effect to this?

**Comment by lonnblad** [comment]
Hey @hansbogert 

Good question, to be honest, I'm not sure why that is in the FAQ.

`testing.M.Run()` would execute all tests in your pkg, so I would assume it was added to the FAQ to show how you can execute godog next to your normal tests.

Maybe we should add a more describing text?

**Comment by hansbogert** [comment]
I am far from a good comment writer, but see 

https://github.com/cucumber/godog/pull/353

We could also opt for just mentioning it somewhere once as a code snippet and  removing it at all the current places.
