### ISSUE TITLE
input/output error when running GoDog after fresh install

### ISSUE THREAD

**Issue by jamesethatcher** [cucumber/godog#358]
Please answer these questions before submitting a bug report.

### What version of godog are you using?
```
Godog version is: v0.10.0
```

### What version of Go are you using?
```
go version go1.15.1 darwin/amd64
```

### What did you do?
If possible, provide a recipe for reproducing the error.

Install GoDog on Mac OS 10.15.6:

`GO111MODULE=on go get github.com/cucumber/godog/cmd/godog@v0.10.0`

Run GoDog in project root:

`~/go/bin/godog`

### What did you expect to see?

Stubs for Gherkin feature.

### What did you see instead?

`fork/exec /Users/<USER>/Desktop/godog/godog.test: input/output error`

**Comment by lonnblad** [comment]
Hi @jamesethatcher

Unfortunately, I don't recognise this issue.

A few questions
Is your project root in the `$GOPATH`?
Is this your project root `/Users/<USER>/Desktop/godog`?
Do you use `go.mod` or another dependency manager?

BR
Fredrik

**Comment by jteng** [comment]
seeing the same error: 
➜  api git:(master) ✗ pwd
/Users/<USER>/Downloads/godog/_examples/api
➜  api git:(master) ✗ godog version.feature
fork/exec /Users/<USER>/Downloads/godog/_examples/api/godog.test: input/output error

**Comment by jteng** [comment]
my bad, need to put the repo on the $GOPATH, resolved

**Comment by lonnblad** [comment]
Will close this issue due to inactivity and since jteng's issue was resolved.

BR
Fredrik
