### ISSUE TITLE
Stepdefinition implementation recommendation is outdated for DocString and Table

### ISSUE THREAD

**Issue by lonnblad** [cucumber/godog#367]
Please answer these questions before submitting a bug report.

### What version of godog are you using?
```
> godog -version
Godog version is: v0.11.0
```

### What version of Go are you using?
```
> go version
go version go1.15.6 darwin/amd64
```

### What did you do?
- Add a step to a feature file including a DocString which has no registered step definition.
- Execute: `godog run`

### What did you expect to see?
```
You can implement step definitions for undefined steps with these snippets:

func theEquals(arg1 string, arg2 *godog.DocString) error {
        return godog.ErrPending
}

func theExistingData(arg1 *godog.DocString) error {
        return godog.ErrPending
}

func InitializeScenario(ctx *godog.ScenarioContext) {
        ctx.Step(`^the "([^"]*)" equals:$`, theEquals)
        ctx.Step(`^the existing data:$`, theExistingData)
}
```

### What did you see instead?
```
You can implement step definitions for undefined steps with these snippets:

func theEquals(arg1 string, arg2 *messages.PickleStepArgument_PickleDocString) error {
        return godog.ErrPending
}

func theExistingData(arg1 *messages.PickleStepArgument_PickleDocString) error {
        return godog.ErrPending
}

func InitializeScenario(ctx *godog.ScenarioContext) {
        ctx.Step(`^the "([^"]*)" equals:$`, theEquals)
        ctx.Step(`^the existing data:$`, theExistingData)
}
```

### Additional context
This is probably also an issue with `godog.Table` replacing `messages.PickleStepArgument_PickleTable`.

**Comment by edumucelli** [comment]
I came here looking for it, cloned the repo to see where the problem was, but I think it was actually fixed in https://github.com/cucumber/godog/commit/5ac22c454cecd246efeec4221729778877a25bf0.
