### ISSUE TITLE
panic on a step returning a wrapped error

### ISSUE THREAD

**Issue by mdelapenya** [cucumber/godog#371]
Please answer these questions before submitting a bug report.

### What version of godog are you using?
```
> godog -version

v0.11.0
```

### What version of Go are you using?
```
> go version

go version go1.14.12 darwin/amd64
```

### What did you do?
I have a step that returns:

```golang
return errors.Wrap(err, content)
```

### What did you expect to see?
The step causes the scenario to fail without panic

### What did you see instead?
The step causes the scenario to fail with panic

### Additional context
Stacktrace:

>reflect.Value.call
	/usr/local/go/src/reflect/value.go:460
reflect.Value.Call
	/usr/local/go/src/reflect/value.go:321
github.com/cucumber/godog/internal/models.(*StepDefinition).Run
	/Users/mdelapenya/sourcecode/pkg/mod/github.com/cucumber/godog@v0.11.0/internal/models/stepdef.go:159
github.com/cucumber/godog.(*suite).runStep
	/Users/mdelapenya/sourcecode/pkg/mod/github.com/cucumber/godog@v0.11.0/suite.go:138
github.com/cucumber/godog.(*suite).runSteps
	/Users/mdelapenya/sourcecode/pkg/mod/github.com/cucumber/godog@v0.11.0/suite.go:225
github.com/cucumber/godog.(*suite).runPickle
	/Users/mdelapenya/sourcecode/pkg/mod/github.com/cucumber/godog@v0.11.0/suite.go:284
github.com/cucumber/godog.(*runner).concurrent.func1
	/Users/mdelapenya/sourcecode/pkg/mod/github.com/cucumber/godog@v0.11.0/run.go:111
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373

**Comment by mdelapenya** [comment]
When I simply return `err`, then there is no panic and godog behaves as expected

**Comment by lonnblad** [comment]
Hi @mdelapenya, thanks for the issue!
Correct me if I'm wrong, but I believe the errors pkg adds a stacktrace to your error, isn't that what we are seeing here?

**Comment by mdelapenya** [comment]
Yes, it's printing the stacktrace, but godog finishes its execution not triggering the afterScenario hooks. Mmmm... It's true that I'm running only one test here, so I tend to think that this is related to #370. Let me do another round of verifications. Thanks!

**Comment by mdelapenya** [comment]
Ok, sorry for the noise. I checked that the stacktrace is part of the output summary after tests are executed, so it works as expected. When I ran multiple scenarios including the one wrapping the error, the the stacktrace appears at the summary too, not stopping the build.

Said that, I'm going to close this because I'm experiencing the expected, right behaviour, which is not a bug.

Thanks!
