### ISSUE TITLE
Unable to get TestStepResult from AfterStep

### ISSUE THREAD

**Issue by wedothings** [cucumber/godog#378]
Please answer these questions before submitting a bug report.

### What version of godog are you using?
```
v0.11.0
```

### What version of Go are you using?
```
go1.16 
```

### What did you do?
I'm trying to get the TestStepFinished.TestStepResult.Status for each step, from an AfterStep func.
By doing the below within the InitializeScenario.

```
func InitializeScenario(s *godog.ScenarioContext) {

    s.AfterStep(func(st *messages.TestStepFinished, err error) {
		    stepResultStatus = st.TestStepResult.Status
	    })
```

### What did you expect to see?

I expected the AfterStep method to compile, and a possible status from the below to be returned on execution.
```
	TestStepResult_UNKNOWN TestStepResult_Status = 0
	TestStepResult_PASSED TestStepResult_Status = 1
	TestStepResult_SKIPPED TestStepResult_Status = 2
```

### What did you see instead?
The AfterStep doesn't compile and returns the below error.
```
Cannot use 'func(st *messages.TestStepFinished, err error) { resultStatus = st.TestStepResult.Status }' (type func(st *messages.TestStepFinished, err error)) as type func(st *Step, err error)
```

Not sure how to obtain values like TestStepFinished and also GherkinDocument_Feature_Step?

**Comment by lonnblad** [comment]
Hi @iannt81, this is currently not possible through the hook API, but I marked this issue as an enhancement. I like the suggestion and I feel this is something that could be available when we do a rework on the hook API.

I would suggest you to put a comment on the API draft posted in #360.

BR
Fredrik

**Comment by iannt81** [comment]
@lonnblad thanks for the response, sure, I'll add to the API draft. Thanks

**Comment by dipaligulhane** [comment]
We are using a workaround for now for this. Surely this enhancement will life easy.

**Comment by iannt81** [comment]
hey @dipaligulhane out of interest, what's your current work around? Do you have an example you could share please? Thanks

**Comment by vearutop** [comment]
@wedothings as a workaround, currently you can get the status from the received `err` 
```go
		switch err {
		case nil:
			status = models.Passed
		case ErrPending:
			status = models.Pending
		default:
			status = models.Failed
		}
```

same way as `godog` does in https://github.com/cucumber/godog/blob/v0.11.0/suite.go#L80-L97.
