### ISSUE TITLE
How to get test step name, scenario name in BeforeScenario() and AfterStep() 

### ISSUE THREAD

**Issue by dipaligulhane** [cucumber/godog#385]
I am trying to use an external reporting tool along with godog. And for the same need to capture:
- scenario title specified in feature file in BeforeScenario()
- step name/title specified in feature file in AfterStep()

I tried looking out for examples in https://github.com/cucumber/godog repo, however did not get any.
Can someone point me to any example if available?
I am using godog version v0.11.0 and go version 1.15.

**Comment by dipaligulhane** [comment]
Got the pointers. Hence closing.

**Comment by lonnblad** [comment]
Hi @dipaligulhane, thanks for the question, glad you found an answer :)

If you think it would be valuable to show this in an example, please create another issue as an ehancement! :)

Thanks!
BR
Fredrik

**Comment by dipaligulhane** [comment]
@lonnblad Yes, it would be good to add an example. I will create an issue for the same.
Also I would like to work on adding this example so will work on that too.
