### ISSUE TITLE
Adding AfterScenario breaks godog command flags

### ISSUE THREAD

**Issue by AaronCasas** [cucumber/godog#386]
Please answer these questions before submitting a bug report.

### What version of godog are you using?
```
> v0.10.0
```

### What version of Go are you using?
```
> go version go1.14.9 darwin/amd64
```

### What did you do?
I have a godog test file. I am attempting to run the command:
`godog --format="${format}" --tags="${test_tags}"`

This works if the test does not have any `AfterStep` or `AfterScenario` defined, but breaks if it does.

### What did you expect to see?
I expect godog to run successfully.
### What did you see instead?
```
flag provided but not defined: -format
Usage of /<path>/godog.test:
<list of all the flags>
```
### Additional context
This problem only occurs if there are `AfterStep` or `AfterScenario` defined. If I comment those out, `godog` works again.

I am not defining any custom godog flags.

**Comment by lonnblad** [comment]
Hi @AaronCasas, thanks for the issue.

From the error you describe, it looks like you are running an executable, `/<path>/godog.test`.
Is that correct and if so, how do you build it?

BR
Fredrik

**Comment by AaronCasas** [comment]
Thanks for the quick response @lonnblad. I'm not doing anything beyond running `godog <args>` in the directory containing my test files.

**Comment by lonnblad** [comment]
hmm, I can't really reproduce it

do you think you could try and reproduce it using a godog example?

**Comment by AaronCasas** [comment]
It turns out this was due to an interaction with something I was calling from within the `AfterScenario` (an in-house prometheus package), not with the `AfterScenario` itself. Sorry for the false alarm, and thanks for the quick responses! I'll close this out.
