### ISSUE TITLE
Updating GoDog to the latest 'Messages-go' release (v16)

### ISSUE THREAD

**Issue by Yellaks** [cucumber/godog#396]
As stated in this issue raised here: https://github.com/cucumber/common/issues/1517 

The 'messages-go' v15 dependency had a security issue, I want to update GoDog to use 'messages-go v16' and remove the security issue.

Update the code, to the latest release of 'Messages-go', v16

**Comment by mattwynne** [comment]
Done in #402

**Comment by Yellaks** [comment]
@mattwynne - thanks for closing this.
Just wondering about using the latest code, is this possible or should I wait until a new release has been published?

**Comment by mattwynne** [comment]
I think if you're able to use the code directly from the git main branch, we'd love the feedback on whether it works. We should be aiming to have that branch in a releasable state at all times.

**Comment by Yellaks** [comment]
@mattwynne - thanks Matt. Unfortunately we need a tagged release, do you have any idea of when the next one will be?

**Comment by mattwynne** [comment]
Ah, OK. @vearutop what are your thoughts about making a release?

**Comment by vearutop** [comment]
@mattwynne I personally prefer short release cycles (even to an extent of tagging every merged PR on `main`), seems we don't have any blocker bugs at the moment, though we have a milestone with 4 open issues: https://github.com/cucumber/godog/milestone/6.

@Yellaks could you try latest `main` in your project(s) to check if there unexpected changes/bugs that we need to consider before release?

```
go get -u github.com/cucumber/godog@48c0e0dd7717fe51d00c8e1794a433e8b76739e8
```

I tried against few of my own projects and it worked without regressions.

I think we can get https://github.com/cucumber/godog/pull/364 merged, review/update the changelog and tag `v0.12.0`.

**Comment by Yellaks** [comment]
@vearutop - sorry I am unable to use the `main` in my project, due to company restrictions; we need to use a tagged version.
Any ideas on when v0.12.0 will be available?

**Comment by vearutop** [comment]
I've created a PR to prepare `godog` for next release https://github.com/cucumber/godog/pull/416, please check.

Hopefully we can have it merged and tagged with `v0.12.0` soon.

**Comment by vearutop** [comment]
@Yellaks release candidate is tagged: https://github.com/cucumber/godog/releases/tag/v0.12.0-rc1. Could you try it with your tests?

**Comment by Yellaks** [comment]
@vearutop I have been able to test the tagged release `v0.12.0-rc1` successfully. Thank you for your help on this :)
