### ISSUE TITLE
Support per-scenario data shared across steps

### ISSUE THREAD

**Issue by noel-yap** [cucumber/godog#397]
**Is your feature request related to a problem? Please describe.**
Sharing data among steps while ensuring each scenario has its own set of data is difficult.

**Describe the solution you'd like**
I would like to be able to share data across steps and ensure that each scenario has its own copy.

**Describe alternatives you've considered**
Currently, I'm using file-level `var`s and initializing them with `ctx.BeforeScenario`. Some of the `var`s are initialized in a `Given` step since their initialization depend on argument values passed into the step.

Since each scenario will be using the same file-level `var`, this implies they won't be able to be run concurrently.

**Comment by mattwynne** [comment]
Is this similar to #360?

**Comment by noel-yap** [comment]
I'm not sure. From what I'm understanding in https://github.com/cucumber/godog/issues/360, the context being passed around is (or should be) immutable. In the use case I have, the context must be mutable so that steps can mutate it.

**Comment by jensklose** [comment]
I'm using the following solution:
Create a struct for your case.
```go
type scenario struct {
	name   string
	cmd    *exec.Cmd
	stdin  io.WriteCloser
	stdout io.ReadCloser
	args   []string
	output []byte
	update chan bool
	tf     feature.TfProject
}
```
Convert the relevant functions into methods with the scenario struct as receiver.

```go
func (s *scenario) iShouldGetOutputWithPattern(arg1 string) error {
	for range s.update {}
	matched, err := regexp.Match(arg1, s.output)
	if err != nil {
		return err
	}
	if !matched {
		return fmt.Errorf("Pattern %s not found in %s", arg1, string(s.output))
	}
	return nil
}
```

Initialize per scenario:
```go
func InitializeScenario(ctx *godog.ScenarioContext) {
	s := &scenario{}
	dir, err := os.MkdirTemp("tmp", "*")
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	s.tf = feature.TfProject{Path: dir}
	s.args = append(s.args, "--chdir", s.tf.Path)
	s.update = make(chan bool, 1)
	ctx.BeforeScenario(func(sc *messages.Pickle) {
		s.name = sc.Name
	})
	ctx.AfterScenario(func(sc *godog.Scenario, err error) {
		s.tf.Cleanup()
	})

	ctx.Step(`^whatever$`, s.whatever)
	ctx.Step(`^I should get output with pattern "([^"]*)"$`, s.iShouldGetOutputWithPattern)
	
}
```

**Comment by titouanfreville** [comment]
I developped a set of helpers arround godog including variable picker && fixtures, you can check if it match your usecases :) https://github.com/elmagician/kactus
