### ISSUE TITLE
Go cached tests with `go test .` don't detect changes in the feature files

### ISSUE THREAD

**Issue by rwngallego-lm** [cucumber/godog#400]
When running `go test .` or `go test ./...` and using godog's TestMain definition, the godog tests are cached and the changes in the `features` files are not detected. If we use the non cachable flags the changes are detected:

```
go test . -count=1

# or
go test ./... -count=1
```

### What version of godog are you using?
```
Godog version is: v0.11.0
```

### What version of Go are you using?
```
go version go1.16.4 darwin/amd64
```

### What did you do?
Run the the regular go tests and godog tests using `go test ./...` or `go test .`, getting a successful result, then change a feature definition to make the tests fail.

### What did you expect to see?
The changes in the features files should invalidate the cached tests, and the test should have failed.

```
go test . -count=1
..F...... 9

--- Failed steps:

#### STEPS HERE

3 scenarios (2 passed, 1 failed)
9 steps (8 passed, 1 failed)
101.515957ms
testing: warning: no tests to run
PASS
FAIL    internal/testing/bdd 0.348s
FAIL

```

### What did you see instead?
The changes are not detected and the tests pass.

```
go test .
ok      internal/testing/bdd (cached) [no tests to run]
```

### Additional context
I've setup TestMain as in the documentation:

```
var opts = godog.Options{
	Output: colors.Colored(os.Stdout),
	Format: "progress", // can define default values
}

func init() {
	godog.BindCommandLineFlags("godog.", &opts)
}

func TestMain(m *testing.M) {
	flag.Parse()
	opts.Paths = flag.Args()

	status := godog.TestSuite{
		Name: "godogs",
		TestSuiteInitializer: InitializeTestSuite,
		ScenarioInitializer:  InitializeScenario,
		Options: &opts,
	}.Run()

	// Optional: Run `testing` package's logic besides godog.
	if st := m.Run(); st > status {
		status = st
	}

	os.Exit(status)
}
```

**Comment by vearutop** [comment]
I think this is expected behavior with idiomatic workaround `-count=1`. I don't think there is a way to control Go tests cache based on feature files.

I'm closing this issue, please feel free to reopen if there are some additional suggestions or ideas.
