### ISSUE TITLE
False version number documented in Readme.md?

### ISSUE THREAD

**Issue by gurix** [cucumber/godog#420]
In Readme.md the command `go get github.com/cucumber/godog/cmd/godog@v0.12.0` is documented but it should be `go get github.com/cucumber/godog/cmd/godog@v0.12.0-rc1`. I am not sure if this is intentional or not?

### What version of Go are you using?
```
> go version
go version go1.16.3 darwin/amd64
```

### What did you do?
I tried to update to v0.12.0

```
> go get github.com/cucumber/godog/cmd/godog@v0.12.0       
```

### What did you expect to see?

```
> go get github.com/cucumber/godog/cmd/godog@v0.12.0       
go: downloading github.com/cucumber/godog v0.12.0
go get: upgraded github.com/cucumber/godog v0.11.0 => v0.12.0
```

### What did you see instead?

```
> go get github.com/cucumber/godog/cmd/godog@v0.12.0       
go get: github.com/cucumber/godog/cmd/godog@v0.12.0: invalid version: unknown revision cmd/godog/v0.12.0 
```

**Comment by karfrank** [comment]
The Readme on the main branch has been updated in preparation for the v0.12.0 release, but it hasn't been released yet.
It should work when you replace `v0.12.0` with `v0.11.0` or any other valid release tag. See https://github.com/cucumber/godog/releases

**Comment by vearutop** [comment]
Now that [`v0.12.0`](https://github.com/cucumber/godog/releases/tag/v0.12.0) is released and documentation is correct again.
