### ISSUE TITLE
Function .After() is called before fuction StepContext().After()

### ISSUE THREAD

**Issue by leonbergr** [cucumber/godog#434]
### What version of godog are you using?
```
> Godog version is: v0.12.1
```

### What version of Go are you using?
```
> go version go1.17 linux/amd64
```

### What did you do?
I have this setup (pseudo code):
```
s.After(func(){ fmt.Println("After scenario") })
s.Stepcontext().After(func() { fmt.Println("After step") })
```

### What did you expect to see?
```
...
After step
After step
After step
After scenario
```

### What did you see instead?
```
...
After step
After step
After scenario
After step
```

### Additional context
It is probably caused by this: https://github.com/cucumber/godog/blob/239a42468acb95a3e4813892a60b6acd2eb45a5b/suite.go#L108-L110

**Comment by vearutop** [comment]
Interesting, thank you for raising this issue, I'll check what's happening.

**Comment by leonbergr** [comment]
Thank you, please let me know if you need additional info.

**Comment by alexrudd** [comment]
Also just hit this same issue 😄

**Comment by vearutop** [comment]
@leonbergr @alexrudd could you check if #444 (branch `after-order`) behaves within your expectations?

You may use branched version with 
```
go install github.com/cucumber/godog/cmd/godog@after-order
``` 
or
```
go get -u github.com/cucumber/godog@after-order
```
depending if you use godog as CLI or as a library.

**Comment by leonbergr** [comment]
I just checked with the master now. It looks ok, thank you!
