### ISSUE TITLE
Unable to run godog's tests

### ISSUE THREAD

**Issue by ALCooper12** [cucumber/godog#447]
Right now I am pairing with @mattwynne and I am trying to make a contribution however godog's tests fail on my windows machine with go version 1.17.3 but it does not fail on his Mac machine with the same go version and same version of the code. If someone could help us understand the error messages from the test, it would be greatly appreciated! 

Here is the gist of the output of running `make test`: 
https://gist.github.com/ALCooper12/27aae59a58651a0378aa56e47a2abac4

**Comment by mxygem** [comment]
Oh shoot, sorry @ALCooper12 ! I totally thought I wrote you a response but I have no idea where it is, sorry! Maybe I'm just misremembering a chat I had with Matt? 🤷 

I don't have a solve for what's going on unfortunately. I have found that [this](https://github.com/cucumber/godog/blob/b850b44b48b7cb1ff1668b2c789084251f6fd81a/internal/formatters/fmt.go#L97) is the line that manages stripping the package name from the output for matching though.

I'm unsure whether or not we're running into a case where somehow that var isn't being set or read correctly when you run the tests, therefore preventing the text from being trimmed as needed.

**Comment by ALCooper12** [comment]
@mxygem No worries at all! So for today, me and @mattwynne updated my WSL Ubuntu terminal that's running on my Windows Machine from Version 1 to Version 2 and my `go env` still outputs:
```arianna@Arianna-PC:/mnt/c/Users/12096/go/src/godog$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\12096\AppData\Local\go-build
set GOENV=C:\Users\12096\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\12096\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\12096\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.3
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\12096\go\src\godog\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\12096\AppData\Local\Temp\go-build3279189581=/tmp/go-build -gno-record-gcc-switches
```

But it shows this output in PowerShell now that I'm using WSL Version 2:
```PS C:\Users\12096\go\src\godog> wsl -l -v
  NAME                   STATE           VERSION
* docker-desktop-data    Stopped         2      
  Ubuntu                 Running         2     
```
And I'm still getting the same errors when running `make test` as before in gist file above

**Comment by ALCooper12** [comment]
After a lot of help from @mxygem un-installing and re-installing WSL version 2, when I run `go env` I get this: 
```
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/arianna/.cache/go-build"
GOENV="/home/arianna/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/arianna/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/arianna/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/arianna/godog/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2097167510=/tmp/go-build -gno-record-gcc-switches"
```
notice that I now see `GOHOSTOS="linux"` instead of `GOHOSTOS=windows` and `GOOS="linux"` instead of `GOOS=windows` when I run `go env` 🎉 

Now all the tests pass after running `sudo apt install build-essential`, `sudo install make`, and finally `make test` with @mattwynne
