### ISSUE TITLE
Access test suite results programmatically, after a test suite run

### ISSUE THREAD

**Issue by zachmandeville** [cucumber/godog#456]
**Is your feature request related to a problem? Please describe.**
I am unable to find an obvious way to achieve the result I want using godog, and so am checking to see if the feature exists or if it could be requested.  I want is to be able to use godog as a library within a larger test runner, and to run multiple test suites against different targets and then combine the results of all these runs into a custom, summarized printout. 

**Describe the solution you'd like**
I would like to be able to  access the results of a test suite after it is run--essentially the cucumber printout but as a golang struct.  For example, if it could be easily accessed from within the afterSuite hook function.

**Describe alternatives you've considered**
My current method I have is to output each of the results to a file, using `godogOpts.Format`.  Then I loop over these files, parse them for the relevant values that I add to my result set, and then write the result set to an additional file.  This doesn't feel the cleanest, though, and opens up potential bugs that could be avoided if the summarizing was part of a suite hook.

**Additional context**
I am still learning this library and so this may be a feature I just couldn't see.  I apologize if so! Also, thank you for your work this library is great!

**Comment by vearutop** [comment]
Hello, I think in your case you can create a [custom formatter](https://github.com/cucumber/godog/blob/main/_examples/custom-formatter/emoji.go) that would collect necessary stats.

Godog allows using multiple formatters, so you can continue using your original formatter.

Also it might be more convenient to collect result into byte buffer instead of files.

Please check the schematic example of how to run multiple suites, hope it helps.

```go
package test

import (
	"bytes"
	"fmt"
	"testing"

	"github.com/cucumber/godog"
)

func TestAllTheThings(t *testing.T) {
	// Register your collectResult custom formatter.

	// Set up the runs, here for sake of an example it is a slice of feature paths.
	var runs []string

	buf := bytes.NewBuffer(nil)
	for _, run := range runs {
		buf.Reset()

		suite := godog.TestSuite{
			ScenarioInitializer: func(s *godog.ScenarioContext) {
				// Register steps.
			},
			Options: &godog.Options{
				Format:   "collectResult,pretty", // Add custom formatter to formatters.
				Paths:    []string{"features/" + run},
				Output:   buf,
				TestingT: t,
			},
		}

		if suite.Run() != 0 {
			fmt.Println(buf.String()) // Flush collected output.

			// Do something about collected result.

			t.Fail()
		}
	}
}
```

**Comment by zachmandeville** [comment]
Ah, this is so helpful, thank you @vearutop !
