### ISSUE TITLE
Godog command returns an error with Go 1.18

### ISSUE THREAD

**Issue by tnerolftnerolf** [cucumber/godog#464]
### 👓 What did you see?

After migration from Go 1.17 to 1.18, when using the godog command, I systematically got "failed to compile testmain package: exit status 1 - output: compile: /tmp/go-build1485890205/b001/importcfg.link:439: unknown directive "modinfo"

### ✅ What did you expect to see?

godog to run available tests

### 📦 Which version are you using?

The problem appeared after upgrading from Go 1.17 to 1.18.
I was using godog v0.12.0, but the problem is still the same on v0.12.4.

I have cloned the godog repo, and the issue also appear when running godog tests.

### 🔬 How could we reproduce it?

1. Install Go 1.18
2. cd  to a directory where your godog tests were correctly passing OK
3. run godog command
4. an error like "failed to compile testmain package: exit status 1 - output: compile: /tmp/go-build1485890205/b001/importcfg.link:439: unknown directive "modinfo" shall be displayed:

**Comment by b-repo** [comment]
exactly the same problem on my side !

**Comment by vearutop** [comment]
Until the issue is resolved, as a workaround I suggest to run `godog` tests via [`go test`](https://github.com/cucumber/godog#subtests-of-testingt).

**Comment by tnerolftnerolf** [comment]
The issue is fixed for me with this version ! Thanks.

**Comment by vearutop** [comment]
New version tagged with a fix: `v0.12.5`.

**Comment by xavimoreno548** [comment]
I was the same problem, and after use `go install github.com/cucumber/godog/cmd/godog@upd-go1.18` with go1.18, this worked.

**Comment by hmoreira-meli** [comment]
This issue still happening with the `godog v0.12.5` and `Go 1.19` :(

**Comment by Wyfy0107** [comment]
I still see this issue in go1.19 I'm using godog v0.12.6
Should this work with go1.19 ?

**Comment by vearutop** [comment]
I just checked with `go install github.com/cucumber/godog/cmd/godog@latest` and `go1.19.3` against `TestMain` setup, and couldn't reproduce the issue.

**Comment by Wyfy0107** [comment]
> I just checked with `go install github.com/cucumber/godog/cmd/godog@latest` and `go1.19.3` against `TestMain` setup, and couldn't reproduce the issue.

Thanks @vearutop I managed to fix it now with `go install`. Previously was using `go get`
