### ISSUE TITLE
Concurrency issue when using a context

### ISSUE THREAD

**Issue by wedothings** [cucumber/godog#472]
### 👓 What did you see?

When running scenarios concurrently, all scenarios seem to be sharing the same testContext.

The testContext is an object used to pass values between steps, the steps add values to the testContext and extract too.

However, all scenarios where attempting to update the map in the testContext at once, which caused the below error

`fatal error: concurrent map iteration and map write`

### ✅ What did you expect to see?

I expected to see multiple scenarios to run concurrently, with each scenario to have its own testContext instance and to only be able to update the testContext relevant for that scenario.
And that one scenario wouldn't interfere with another scenarios testContext.

### 📦 Which tool/library version are you using?

github.com/cucumber/godog v0.12.5
go 1.16

### 🔬 How could we reproduce it?

```
opts = godog.Options{
		Output:      colors.Colored(os.Stdout),
		Format:      "pretty",
		Concurrency: 13,
		Randomize:   time.Now().UTC().UnixNano(),
}
```

A step like.. `s.Step(`^a customer$`, testContext.aCustomer)`

The `testContext` has a map in it, which is added to and extracted from by steps throughout the scenario

```
type TestContext struct {
	customer       map[string]string
```

### 📚 Any additional context?

Each scenario populates the testContext with different values, specific for the scenario.

So if when you enable concurrency, the scenarios all begin to use the same testContext passed between the steps. Then I guess this means that concurrency is not compatible with a scenario unique testContext object being passed between steps. Is that right?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by stevecager** [comment]
Hey @wedothings, I would also like to run tests in parallel but am finding that using a shared testContext means variables from one test/scenario get overwritten by variables from another. 

Is it something I am doing wrong or does the current version of Godog need enhancing to accommodate this use case?

**Comment by wedothings** [comment]
Hey @stevecager that's the same behaviour I'm seeing. 

I don't think it's anything you're doing wrong.

I guessing it's a limitation of Godog in it's current state, however, I'd like confirmation from a maintainer first?

Additionally, if it is a limitation, I think it's worth calling out in the documentation or readme.

**Comment by vearutop** [comment]
_TL;DR_: use`context.Context` to pass state between scenarios.

It is not trivial to implement a stateful step function using globally shared data (e.g. `customer map[string]string`) that is safe to use under concurrency.

However, there is an easier and more straightforward way, you can use `ctx context.Context` as first argument of your step function and as a returned value to propagate state between the steps.

Here is a small example from README.
```
type cntCtxKey struct{} // Key for a particular context value type.

s.Step("^I have a random number of godogs$", func(ctx context.Context) context.Context {
	// Creating a random number of godog and storing it in context for future reference.
	cnt := rand.Int()
	Godogs = cnt
	return context.WithValue(ctx, cntCtxKey{}, cnt)
})

s.Step("I eat all available godogs", func(ctx context.Context) error {
	// Getting previously stored number of godogs from context.
	cnt := ctx.Value(cntCtxKey{}).(uint32)
	if Godogs < cnt {
		return errors.New("can't eat more than I have")
	}
	Godogs -= cnt
	return nil
})
```

Each scenario runs in its own `context.Context`, so there is naturally no concurrency clash and no need for explicit synchronization.

Context that is returned from step function (and hook functions too) acts as an input for the next step.

**Comment by vearutop** [comment]
Please check if [updated README](https://github.com/cucumber/godog/blob/update-readme/README.md) makes more sense in how to pass state safely while running concurrent scenarios.
