### ISSUE TITLE
Correct test coverage report not generating in GODOG when used with go test

### ISSUE THREAD

**Issue by pulkitent** [cucumber/godog#483]
### 👓 What did you see?

- Empty **coverage.txt** file (with only one line in that file as `mode: atomic`
- Test was passing but the command prompt log contained `coverage: [no statements]`

### ✅ What did you expect to see?

- **coverage.txt** file with proper coverage details

### 📦 Which tool/library version are you using?

Godog - v0.12.5

### 🔬 How could we reproduce it?

`go test -test.v -test.run ^TestFeatures$ -race -coverprofile=coverage.txt`

**Comment by pulkitent** [comment]
Took reference from [here](https://github.com/cucumber/godog/issues/155) but not able to generate proper report

**Comment by vearutop** [comment]
By default `go test` only collects coverage in the package that owns the test, please try with `-coverpkg=./...` to enable coverage collection across sub packages too.

**Comment by pulkitent** [comment]
@vearutop used below command 
`go test -test.v -test.run ^TestFeatures$ -coverpkg=./... -race -coverprofile=coverage.txt`

But got no success. My PWD is `/Users/pulkitgupta/Desktop/<project_name>/godogs` from where I am running above command

My folder structure is as shared in SS

<img width="310" alt="Screenshot 2022-06-30 at 3 43 26 PM" src="https://user-images.githubusercontent.com/9362179/176652977-8924168a-f423-4820-a470-272f8658334c.png">

Coverage.txt is as below

<img width="1418" alt="Screenshot 2022-06-30 at 3 39 33 PM" src="https://user-images.githubusercontent.com/9362179/176653167-02bbff79-7ea5-4b78-8b25-60a50f0fec79.png">

**Comment by vearutop** [comment]
Ah, if you're running test from a subpackage then your `-coverpkg` should refer project directory (parent), e.g. relative
`-coverpkg=../...` or more reliable absolute `-coverpkg=<your-project-module>/...`.

**Comment by pulkitent** [comment]
@vearutop, I used this command `go test -test.v -test.run ^TestFeatures$ -coverpkg=../... -coverprofile=coverage.txt -covermode=set` & It worked.

But just wanted to confirm whether the coverage report I am getting by running the above command is the coverage of only the Integration tests (Godog)?
Or
That report is the total coverage of all the tests (Unit & Integration both) that I have in my repo?

**Comment by vearutop** [comment]
This will be a coverage report of your tests that match `^TestFeatures$` name, so I assume that would only be your integration tests.

However, removing integration tests from unit coverage might be more complicated. 

A few strategies of running unit and integration tests separately are discussed here:
https://stackoverflow.com/questions/25965584/separating-unit-tests-and-integration-tests-in-go

**Comment by pulkitent** [comment]
@vearutop, thanks for your help here. In actuality, I was missing the knowledge here :)

Hopefully, this conversation will be helpful for other newbies folks like me in future

**PS: Closing the issue :)**
