### ISSUE TITLE
Error "undefined: os.ReadFile" when trying to install GoDog v0.12.5 on Ubuntu 20.04

### ISSUE THREAD

**Issue by MarcusQA** [cucumber/godog#485]
### 👓 What did you see?

Error "undefined: os.ReadFile" when trying to install GoDog v0.12.5 on Ubuntu 20.04 using the following command:

```
$ go get github.com/cucumber/godog/cmd/godog@v0.12.5
go: finding github.com v0.12.5
go: finding github.com/cucumber/godog/cmd/godog v0.12.5
go: finding github.com/cucumber/godog/cmd v0.12.5
go: finding github.com/cucumber v0.12.5
# github.com/cucumber/godog/internal/builder
../../go/pkg/mod/github.com/cucumber/godog@v0.12.5/internal/builder/builder.go:243:15: undefined: os.ReadFile
```

Note that I see no such error when I install v0.12.4 using the following command:
```
$ go get github.com/cucumber/godog/cmd/godog@v0.12.4
```

### ✅ What did you expect to see?

No error when running the command to install GoDog v0.12.5

### 📦 Which tool/library version are you using?

GoDog v0.12.5

### 🔬 How could we reproduce it?

On Ubuntu 20.04 run the following command:
```
$ go get github.com/cucumber/godog/cmd/godog@v0.12.5
```

### 📚 Any additional context?

![image](https://user-images.githubusercontent.com/23223411/177740685-fd31eab0-7629-40b0-ae37-768d99353500.png)

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by vearutop** [comment]
It seems you're having an old version of Go (less than 1.16), you can check version with `go version`.

Go has a policy of supporting two latest minor versions and `godog` sticks to that policy too. It is unfortunate that `apt` package of Go in ubuntu is usually older than minimal supported version.

**Comment by MarcusQA** [comment]
Thanks for your prompt response, @vearutop. Yeah you're right:
![image](https://user-images.githubusercontent.com/23223411/177746480-045696cd-1410-4756-95ec-20107e026151.png)

**Comment by wichert** [comment]
Should this ticket be closed?
