### ISSUE TITLE
Execution of Scenarios based on the whether the previous scenario was passed or failed

### ISSUE THREAD

**Issue by wasim-nihal** [cucumber/godog#501]
### 🤔 What's the problem you're trying to solve?
Trying to create a kind of dependency among the scenarios. If for example, we want to decide whether to run
a test scenario based on the status of the previous scenario (passed/failed), there is no easy solution.
 For example, let us consider scenario-1 is for the installation of service and scenario-2 is performing an operation on an installed service. Here if the installation scenario (scenario-1) itself fails, there is no need to test for scenario-2.

### ✨ What's your proposed solution?
There should be some kind of annotation like `@DependsOn(<name of the scenario>)` while defining the scenario.
For example:
 ```
Scenario: Eat 5 out of 12
    Given there are 12 godogs
    When I eat 5
    Then there should be 7 remaining

  @DependsOn(Eat 5 out of 12)
  Scenario: Eat 6 out of 12
    Given there are 12 godogs
    When I eat 6
    Then there should be 6 remaining
```

Here, the scenario "Eat 6 out of 12" should be skipped if the scenario "Eat 5 out of 12" was failed.

### ⛏ Have you considered any alternatives or workarounds?
One of the workarounds followed is to set  some kind of flag in a scenario and check for it's value in the subsequent dependent step functions. This will not prevent the test of the dependent scenario, but will error out at the beginning itself. 

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by aslakhellesoy** [comment]
This feature request has come up regularly since Cucumber was created. We're not going to allow dependencies between scenarios.

Do we have a FAQ anywhere where we explain:

1. Why this is a bad idea to begin with
2. Why we won't implement it in Cucumber
