### ISSUE TITLE
Running as subtest does not respect Strict option

### ISSUE THREAD

**Issue by davidedmondsMPG** [cucumber/godog#536]
### 👓 What did you see?

Running a suite with steps that return `godog.ErrPending` in subtest mode fails the test regardless of the `Strict` option.

### ✅ What did you expect to see?

Running a suite with steps that return `godog.ErrPending` in subtest mode:
- fails the test if the `Strict` option is set to true
- does not fail the test (maybe skips with `t.Skip()`) if the `Strict` option is set to false

### 📦 Which tool/library version are you using?

Godog v0.12.6
Golang v1.19.4 darwin/amd64

### 🔬 How could we reproduce it?

1. Create a simple feature with at least one step
2. Create a subtest mode test to run the feature, setting the `Strict` option to `false`
3. Run the test to get the generated stubs
4. Copy-paste the output into the appropriate places in the test file
5. Run the test again - the subtest is marked as failed.

### 📚 Any additional context?

If the `TestingT` parameter is removed then the `Strict` flag behaves as I'd expect.

Raising as an issue as I'm not 100% sure if this behaviour's intentional. If accepted, am happy to contribute a fix.

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by roskee** [comment]
Thanks. I personally don't think it should fail. But am not sure if it was intentional.
