### ISSUE TITLE
Why Getting total scenarios as 6 while I am having total 5 scenarios  

### ISSUE THREAD

**Issue by ksoniAngel** [cucumber/godog#581]
<img width="344" alt="Screenshot 2023-10-23 at 11 11 26 AM" src="https://github.com/cucumber/godog/assets/139200565/a1926a5b-95f8-4b8a-aa33-6c1b9606d3ec">

I am running test as go test -v

getting total 5 scenrioes in which 2 passed and 4 fails.

**Expected result := 5 (1 passed, 4 failed)**

**Comment by roskee** [comment]
Hi, what was the version of godg you were using?

**Comment by ksoniAngel** [comment]
@roskee  I am running this test by using go test -v for 2 weeks


I installed godog today, It's version is 0.13.0 

But this problem is faing since two weeks, some time I got correct number of pass or failed test cases and some time I not.

If any other info required please let me know

**Comment by roskee** [comment]
@ksoniAngel I looked into it and it is a bug. I have created a pull request to fix it. But for now, know that it is the `passed` count that is incorrect. In your case what you expected was indeed the correct result that should have been shown. Thanks for pointing it out :pray:
