### ISSUE TITLE
step function support return a nil Context with error

### ISSUE THREAD

**Issue by Milk-Tang** [cucumber/godog#592]
### 👓 What did you see?
panic occured while I return (nil, err) in the step function

### ✅ What did you expect to see?
When I return a nil Context and non empty error, no panic error occurs

### 📦 Which tool/library version are you using?
v0.12.6

### 🔬 How could we reproduce it?
Run this step
```go
func StepError(ctx context.Context) (context.Context, err) {
    return nil, errors.New("step failed")
}
```

**Comment by o-brunofernandes** [comment]
Did you get an answer on this?

**Comment by Johnlon** [comment]
You do get an error IIRC, but it's pretty horrible error caused by a cast if I recall and the cause isn't at all obvious

**Comment by Milk-Tang** [comment]
I think this has been resolved in https://github.com/cucumber/godog/pull/647
