### ISSUE TITLE
Broken link in „help wanted” issue

### ISSUE THREAD

**Issue by tadeek** [cucumber/godog#622]
### 👓 What did you see?

404 when clickink triage link here https://github.com/cucumber/godog/issues/406#issue-940984138

### ✅ What did you expect to see?

Content of file

### 📦 Which tool/library version are you using?

N/a

### 🔬 How could we reproduce it?

go here https://github.com/cucumber/godog/issues/406#issue-940984138 qnd click on „triage”

**Comment by mpkorstanje** [comment]
Cheers! Fixed. Well, I removed the link. The document doesn't exist anymore.
