### ISSUE TITLE
godog should report failure if ambiguous matching steps are found

### ISSUE THREAD

**Issue by Johnlon** [cucumber/godog#635]
Addressed by PR https://github.com/cucumber/godog/pull/636

### 🤔 What's the problem you're trying to solve?

I want my steps to register an error if there are multiple matching steps.
"Ambiguous step def"

### ✨ What's your proposed solution?

Cause godog to abort if multiple matches are found.
Currentlly it returns the first match so this would be a breaking change for some unsuspecting users of godog.

### 📚 Any additional context?

This proposal would be consistent with other languages

**Comment by Johnlon** [comment]
@mattwynne hi Matt what's the best way to get a quick conversation on this?
I think it's uncontroversial but is a potentially breaking change for those who unwittingly have clashing steps.
Also there is the question of how and where to put a test.

I have fixed this in my own local fork to avoid further embarrassment, but I don't have a PR because my other PR 634 is blocking up my GitHub. And 634 needs a whole separate conversation.

**Comment by vearutop** [comment]
Throwing an error in such case sounds good to me. I think this behavior can be put under [`Strict`](https://github.com/cucumber/godog/blob/v0.14.1/internal/flags/options.go#L42) mode to reduce compatibility impact.

**Comment by Johnlon** [comment]
@vearutop    hi take a look - at the related pr

Addressed by PR https://github.com/cucumber/godog/pull/636Addressed by PR https://github.com/cucumber/godog/pull/636

**Comment by Johnlon** [comment]
Merged

**Comment by Johnlon** [comment]
@vearutop thanks

**Comment by noodnik2** [comment]
Is there a plan to roll this out?

**Comment by Johnlon** [comment]
I found last week I need to make a fix.
cant write at the moment as no time
will do a fix this weekend

**Comment by noodnik2** [comment]
Also see [PR-642](https://github.com/cucumber/godog/pull/642)
